// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cluster_state.proto

package mq

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import client "eventter.io/mq/client"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

import time "time"

import github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ClusterState struct {
	Index                uint64              `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Namespaces           []*ClusterNamespace `protobuf:"bytes,2,rep,name=namespaces" json:"namespaces,omitempty"`
	OpenSegments         []*ClusterSegment   `protobuf:"bytes,3,rep,name=open_segments,json=openSegments" json:"open_segments,omitempty"`
	ClosedSegments       []*ClusterSegment   `protobuf:"bytes,4,rep,name=closed_segments,json=closedSegments" json:"closed_segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ClusterState) Reset()         { *m = ClusterState{} }
func (m *ClusterState) String() string { return proto.CompactTextString(m) }
func (*ClusterState) ProtoMessage()    {}
func (*ClusterState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_b2582f435426ca9d, []int{0}
}
func (m *ClusterState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterState.Merge(dst, src)
}
func (m *ClusterState) XXX_Size() int {
	return m.Size()
}
func (m *ClusterState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterState.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterState proto.InternalMessageInfo

func (m *ClusterState) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ClusterState) GetNamespaces() []*ClusterNamespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *ClusterState) GetOpenSegments() []*ClusterSegment {
	if m != nil {
		return m.OpenSegments
	}
	return nil
}

func (m *ClusterState) GetClosedSegments() []*ClusterSegment {
	if m != nil {
		return m.ClosedSegments
	}
	return nil
}

type ClusterNamespace struct {
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Topics               []*ClusterTopic         `protobuf:"bytes,2,rep,name=topics" json:"topics,omitempty"`
	ConsumerGroups       []*ClusterConsumerGroup `protobuf:"bytes,3,rep,name=consumer_groups,json=consumerGroups" json:"consumer_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ClusterNamespace) Reset()         { *m = ClusterNamespace{} }
func (m *ClusterNamespace) String() string { return proto.CompactTextString(m) }
func (*ClusterNamespace) ProtoMessage()    {}
func (*ClusterNamespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_b2582f435426ca9d, []int{1}
}
func (m *ClusterNamespace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterNamespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterNamespace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterNamespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterNamespace.Merge(dst, src)
}
func (m *ClusterNamespace) XXX_Size() int {
	return m.Size()
}
func (m *ClusterNamespace) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterNamespace.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterNamespace proto.InternalMessageInfo

func (m *ClusterNamespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterNamespace) GetTopics() []*ClusterTopic {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *ClusterNamespace) GetConsumerGroups() []*ClusterConsumerGroup {
	if m != nil {
		return m.ConsumerGroups
	}
	return nil
}

type ClusterTopic struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string        `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Shards               uint32        `protobuf:"varint,3,opt,name=shards,proto3" json:"shards,omitempty"`
	Retention            time.Duration `protobuf:"bytes,4,opt,name=retention,stdduration" json:"retention"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClusterTopic) Reset()         { *m = ClusterTopic{} }
func (m *ClusterTopic) String() string { return proto.CompactTextString(m) }
func (*ClusterTopic) ProtoMessage()    {}
func (*ClusterTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_b2582f435426ca9d, []int{2}
}
func (m *ClusterTopic) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterTopic.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterTopic.Merge(dst, src)
}
func (m *ClusterTopic) XXX_Size() int {
	return m.Size()
}
func (m *ClusterTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterTopic.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterTopic proto.InternalMessageInfo

func (m *ClusterTopic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterTopic) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ClusterTopic) GetShards() uint32 {
	if m != nil {
		return m.Shards
	}
	return 0
}

func (m *ClusterTopic) GetRetention() time.Duration {
	if m != nil {
		return m.Retention
	}
	return 0
}

type ClusterConsumerGroup struct {
	Name                 string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bindings             []*ClusterConsumerGroup_Binding `protobuf:"bytes,2,rep,name=bindings" json:"bindings,omitempty"`
	Shards               uint32                          `protobuf:"varint,3,opt,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ClusterConsumerGroup) Reset()         { *m = ClusterConsumerGroup{} }
func (m *ClusterConsumerGroup) String() string { return proto.CompactTextString(m) }
func (*ClusterConsumerGroup) ProtoMessage()    {}
func (*ClusterConsumerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_b2582f435426ca9d, []int{3}
}
func (m *ClusterConsumerGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterConsumerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterConsumerGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterConsumerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterConsumerGroup.Merge(dst, src)
}
func (m *ClusterConsumerGroup) XXX_Size() int {
	return m.Size()
}
func (m *ClusterConsumerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterConsumerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterConsumerGroup proto.InternalMessageInfo

func (m *ClusterConsumerGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterConsumerGroup) GetBindings() []*ClusterConsumerGroup_Binding {
	if m != nil {
		return m.Bindings
	}
	return nil
}

func (m *ClusterConsumerGroup) GetShards() uint32 {
	if m != nil {
		return m.Shards
	}
	return 0
}

type ClusterConsumerGroup_Binding struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	RoutingKey           string   `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterConsumerGroup_Binding) Reset()         { *m = ClusterConsumerGroup_Binding{} }
func (m *ClusterConsumerGroup_Binding) String() string { return proto.CompactTextString(m) }
func (*ClusterConsumerGroup_Binding) ProtoMessage()    {}
func (*ClusterConsumerGroup_Binding) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_b2582f435426ca9d, []int{3, 0}
}
func (m *ClusterConsumerGroup_Binding) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterConsumerGroup_Binding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterConsumerGroup_Binding.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterConsumerGroup_Binding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterConsumerGroup_Binding.Merge(dst, src)
}
func (m *ClusterConsumerGroup_Binding) XXX_Size() int {
	return m.Size()
}
func (m *ClusterConsumerGroup_Binding) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterConsumerGroup_Binding.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterConsumerGroup_Binding proto.InternalMessageInfo

func (m *ClusterConsumerGroup_Binding) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ClusterConsumerGroup_Binding) GetRoutingKey() string {
	if m != nil {
		return m.RoutingKey
	}
	return ""
}

type ClusterSegment struct {
	TopicNamespace       string               `protobuf:"bytes,1,opt,name=topic_namespace,json=topicNamespace,proto3" json:"topic_namespace,omitempty"`
	TopicName            string               `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	FirstMessageId       []byte               `protobuf:"bytes,3,opt,name=first_message_id,json=firstMessageId,proto3" json:"first_message_id,omitempty"`
	LastMessageId        []byte               `protobuf:"bytes,4,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	Nodes                ClusterSegment_Nodes `protobuf:"bytes,5,opt,name=nodes" json:"nodes"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClusterSegment) Reset()         { *m = ClusterSegment{} }
func (m *ClusterSegment) String() string { return proto.CompactTextString(m) }
func (*ClusterSegment) ProtoMessage()    {}
func (*ClusterSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_b2582f435426ca9d, []int{4}
}
func (m *ClusterSegment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterSegment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterSegment.Merge(dst, src)
}
func (m *ClusterSegment) XXX_Size() int {
	return m.Size()
}
func (m *ClusterSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterSegment.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterSegment proto.InternalMessageInfo

func (m *ClusterSegment) GetTopicNamespace() string {
	if m != nil {
		return m.TopicNamespace
	}
	return ""
}

func (m *ClusterSegment) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ClusterSegment) GetFirstMessageId() []byte {
	if m != nil {
		return m.FirstMessageId
	}
	return nil
}

func (m *ClusterSegment) GetLastMessageId() []byte {
	if m != nil {
		return m.LastMessageId
	}
	return nil
}

func (m *ClusterSegment) GetNodes() ClusterSegment_Nodes {
	if m != nil {
		return m.Nodes
	}
	return ClusterSegment_Nodes{}
}

type ClusterSegment_Nodes struct {
	Primary              uint64   `protobuf:"varint,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Replicating          []uint64 `protobuf:"varint,2,rep,packed,name=replicating" json:"replicating,omitempty"`
	Done                 []uint64 `protobuf:"varint,3,rep,packed,name=done" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterSegment_Nodes) Reset()         { *m = ClusterSegment_Nodes{} }
func (m *ClusterSegment_Nodes) String() string { return proto.CompactTextString(m) }
func (*ClusterSegment_Nodes) ProtoMessage()    {}
func (*ClusterSegment_Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_b2582f435426ca9d, []int{4, 0}
}
func (m *ClusterSegment_Nodes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterSegment_Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterSegment_Nodes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterSegment_Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterSegment_Nodes.Merge(dst, src)
}
func (m *ClusterSegment_Nodes) XXX_Size() int {
	return m.Size()
}
func (m *ClusterSegment_Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterSegment_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterSegment_Nodes proto.InternalMessageInfo

func (m *ClusterSegment_Nodes) GetPrimary() uint64 {
	if m != nil {
		return m.Primary
	}
	return 0
}

func (m *ClusterSegment_Nodes) GetReplicating() []uint64 {
	if m != nil {
		return m.Replicating
	}
	return nil
}

func (m *ClusterSegment_Nodes) GetDone() []uint64 {
	if m != nil {
		return m.Done
	}
	return nil
}

type Command struct {
	// Types that are valid to be assigned to Command:
	//	*Command_ConfigureTopic
	Command              isCommand_Command `protobuf_oneof:"command"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_b2582f435426ca9d, []int{5}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Command.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return m.Size()
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

type isCommand_Command interface {
	isCommand_Command()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Command_ConfigureTopic struct {
	ConfigureTopic *client.ConfigureTopicRequest `protobuf:"bytes,1,opt,name=configure_topic,json=configureTopic,oneof"`
}

func (*Command_ConfigureTopic) isCommand_Command() {}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Command) GetConfigureTopic() *client.ConfigureTopicRequest {
	if x, ok := m.GetCommand().(*Command_ConfigureTopic); ok {
		return x.ConfigureTopic
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Command) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Command_OneofMarshaler, _Command_OneofUnmarshaler, _Command_OneofSizer, []interface{}{
		(*Command_ConfigureTopic)(nil),
	}
}

func _Command_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Command)
	// command
	switch x := m.Command.(type) {
	case *Command_ConfigureTopic:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConfigureTopic); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Command.Command has unexpected type %T", x)
	}
	return nil
}

func _Command_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Command)
	switch tag {
	case 1: // command.configure_topic
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(client.ConfigureTopicRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Command_ConfigureTopic{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Command_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Command)
	// command
	switch x := m.Command.(type) {
	case *Command_ConfigureTopic:
		s := proto.Size(x.ConfigureTopic)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ClusterState)(nil), "io.eventter.mq.ClusterState")
	proto.RegisterType((*ClusterNamespace)(nil), "io.eventter.mq.ClusterNamespace")
	proto.RegisterType((*ClusterTopic)(nil), "io.eventter.mq.ClusterTopic")
	proto.RegisterType((*ClusterConsumerGroup)(nil), "io.eventter.mq.ClusterConsumerGroup")
	proto.RegisterType((*ClusterConsumerGroup_Binding)(nil), "io.eventter.mq.ClusterConsumerGroup.Binding")
	proto.RegisterType((*ClusterSegment)(nil), "io.eventter.mq.ClusterSegment")
	proto.RegisterType((*ClusterSegment_Nodes)(nil), "io.eventter.mq.ClusterSegment.Nodes")
	proto.RegisterType((*Command)(nil), "io.eventter.mq.Command")
}
func (m *ClusterState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterState) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Index))
	}
	if len(m.Namespaces) > 0 {
		for _, msg := range m.Namespaces {
			dAtA[i] = 0x12
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.OpenSegments) > 0 {
		for _, msg := range m.OpenSegments {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ClosedSegments) > 0 {
		for _, msg := range m.ClosedSegments {
			dAtA[i] = 0x22
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ClusterNamespace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterNamespace) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Topics) > 0 {
		for _, msg := range m.Topics {
			dAtA[i] = 0x12
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ConsumerGroups) > 0 {
		for _, msg := range m.ConsumerGroups {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ClusterTopic) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterTopic) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if m.Shards != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Shards))
	}
	dAtA[i] = 0x22
	i++
	i = encodeVarintClusterState(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdDuration(m.Retention)))
	n1, err := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.Retention, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	return i, nil
}

func (m *ClusterConsumerGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterConsumerGroup) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Bindings) > 0 {
		for _, msg := range m.Bindings {
			dAtA[i] = 0x12
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Shards != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Shards))
	}
	return i, nil
}

func (m *ClusterConsumerGroup_Binding) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterConsumerGroup_Binding) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TopicName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.TopicName)))
		i += copy(dAtA[i:], m.TopicName)
	}
	if len(m.RoutingKey) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.RoutingKey)))
		i += copy(dAtA[i:], m.RoutingKey)
	}
	return i, nil
}

func (m *ClusterSegment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterSegment) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TopicNamespace) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.TopicNamespace)))
		i += copy(dAtA[i:], m.TopicNamespace)
	}
	if len(m.TopicName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.TopicName)))
		i += copy(dAtA[i:], m.TopicName)
	}
	if len(m.FirstMessageId) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.FirstMessageId)))
		i += copy(dAtA[i:], m.FirstMessageId)
	}
	if len(m.LastMessageId) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.LastMessageId)))
		i += copy(dAtA[i:], m.LastMessageId)
	}
	dAtA[i] = 0x2a
	i++
	i = encodeVarintClusterState(dAtA, i, uint64(m.Nodes.Size()))
	n2, err := m.Nodes.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	return i, nil
}

func (m *ClusterSegment_Nodes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterSegment_Nodes) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Primary != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Primary))
	}
	if len(m.Replicating) > 0 {
		dAtA4 := make([]byte, len(m.Replicating)*10)
		var j3 int
		for _, num := range m.Replicating {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(j3))
		i += copy(dAtA[i:], dAtA4[:j3])
	}
	if len(m.Done) > 0 {
		dAtA6 := make([]byte, len(m.Done)*10)
		var j5 int
		for _, num := range m.Done {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(j5))
		i += copy(dAtA[i:], dAtA6[:j5])
	}
	return i, nil
}

func (m *Command) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Command) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Command != nil {
		nn7, err := m.Command.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn7
	}
	return i, nil
}

func (m *Command_ConfigureTopic) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.ConfigureTopic != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.ConfigureTopic.Size()))
		n8, err := m.ConfigureTopic.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	return i, nil
}
func encodeVarintClusterState(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ClusterState) Size() (n int) {
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovClusterState(uint64(m.Index))
	}
	if len(m.Namespaces) > 0 {
		for _, e := range m.Namespaces {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	if len(m.OpenSegments) > 0 {
		for _, e := range m.OpenSegments {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	if len(m.ClosedSegments) > 0 {
		for _, e := range m.ClosedSegments {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	return n
}

func (m *ClusterNamespace) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	if len(m.Topics) > 0 {
		for _, e := range m.Topics {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	if len(m.ConsumerGroups) > 0 {
		for _, e := range m.ConsumerGroups {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	return n
}

func (m *ClusterTopic) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	if m.Shards != 0 {
		n += 1 + sovClusterState(uint64(m.Shards))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.Retention)
	n += 1 + l + sovClusterState(uint64(l))
	return n
}

func (m *ClusterConsumerGroup) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	if len(m.Bindings) > 0 {
		for _, e := range m.Bindings {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	if m.Shards != 0 {
		n += 1 + sovClusterState(uint64(m.Shards))
	}
	return n
}

func (m *ClusterConsumerGroup_Binding) Size() (n int) {
	var l int
	_ = l
	l = len(m.TopicName)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = len(m.RoutingKey)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}

func (m *ClusterSegment) Size() (n int) {
	var l int
	_ = l
	l = len(m.TopicNamespace)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = len(m.TopicName)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = len(m.FirstMessageId)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = len(m.LastMessageId)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = m.Nodes.Size()
	n += 1 + l + sovClusterState(uint64(l))
	return n
}

func (m *ClusterSegment_Nodes) Size() (n int) {
	var l int
	_ = l
	if m.Primary != 0 {
		n += 1 + sovClusterState(uint64(m.Primary))
	}
	if len(m.Replicating) > 0 {
		l = 0
		for _, e := range m.Replicating {
			l += sovClusterState(uint64(e))
		}
		n += 1 + sovClusterState(uint64(l)) + l
	}
	if len(m.Done) > 0 {
		l = 0
		for _, e := range m.Done {
			l += sovClusterState(uint64(e))
		}
		n += 1 + sovClusterState(uint64(l)) + l
	}
	return n
}

func (m *Command) Size() (n int) {
	var l int
	_ = l
	if m.Command != nil {
		n += m.Command.Size()
	}
	return n
}

func (m *Command_ConfigureTopic) Size() (n int) {
	var l int
	_ = l
	if m.ConfigureTopic != nil {
		l = m.ConfigureTopic.Size()
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}

func sovClusterState(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozClusterState(x uint64) (n int) {
	return sovClusterState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClusterState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespaces", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespaces = append(m.Namespaces, &ClusterNamespace{})
			if err := m.Namespaces[len(m.Namespaces)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenSegments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OpenSegments = append(m.OpenSegments, &ClusterSegment{})
			if err := m.OpenSegments[len(m.OpenSegments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClosedSegments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClosedSegments = append(m.ClosedSegments, &ClusterSegment{})
			if err := m.ClosedSegments[len(m.ClosedSegments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterNamespace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterNamespace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterNamespace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Topics = append(m.Topics, &ClusterTopic{})
			if err := m.Topics[len(m.Topics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerGroups", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerGroups = append(m.ConsumerGroups, &ClusterConsumerGroup{})
			if err := m.ConsumerGroups[len(m.ConsumerGroups)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterTopic) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterTopic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterTopic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shards", wireType)
			}
			m.Shards = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Shards |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Retention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.Retention, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterConsumerGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterConsumerGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterConsumerGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bindings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bindings = append(m.Bindings, &ClusterConsumerGroup_Binding{})
			if err := m.Bindings[len(m.Bindings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shards", wireType)
			}
			m.Shards = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Shards |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterConsumerGroup_Binding) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Binding: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Binding: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TopicName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoutingKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterSegment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterSegment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterSegment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicNamespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TopicNamespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TopicName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstMessageId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstMessageId = append(m.FirstMessageId[:0], dAtA[iNdEx:postIndex]...)
			if m.FirstMessageId == nil {
				m.FirstMessageId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMessageId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastMessageId = append(m.LastMessageId[:0], dAtA[iNdEx:postIndex]...)
			if m.LastMessageId == nil {
				m.LastMessageId = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Nodes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterSegment_Nodes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Nodes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Nodes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Primary", wireType)
			}
			m.Primary = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Primary |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Replicating = append(m.Replicating, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthClusterState
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowClusterState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Replicating = append(m.Replicating, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicating", wireType)
			}
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Done = append(m.Done, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthClusterState
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowClusterState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Done = append(m.Done, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Done", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Command) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Command: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Command: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigureTopic", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &client.ConfigureTopicRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Command = &Command_ConfigureTopic{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClusterState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthClusterState
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipClusterState(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthClusterState = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClusterState   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("cluster_state.proto", fileDescriptor_cluster_state_b2582f435426ca9d) }

var fileDescriptor_cluster_state_b2582f435426ca9d = []byte{
	// 654 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xae, 0x53, 0xa7, 0x69, 0x4e, 0xda, 0xa4, 0x9a, 0x1b, 0xdd, 0x9b, 0x1b, 0x41, 0x1a, 0x45,
	0x05, 0xb2, 0x40, 0x8e, 0x54, 0x78, 0x80, 0x92, 0x20, 0xb5, 0x15, 0x6a, 0x85, 0x5c, 0x24, 0x24,
	0x36, 0x96, 0x6b, 0x9f, 0x18, 0x8b, 0x78, 0xc6, 0x99, 0x19, 0x23, 0xf2, 0x16, 0xb0, 0xe3, 0x1d,
	0x78, 0x0e, 0xa4, 0x2e, 0xd9, 0xb1, 0x03, 0x54, 0x5e, 0x81, 0x07, 0x40, 0x33, 0x63, 0x37, 0x49,
	0x69, 0x50, 0x77, 0x73, 0xbe, 0xf9, 0xce, 0x77, 0xfe, 0xe1, 0x9f, 0x60, 0x92, 0x09, 0x89, 0xdc,
	0x13, 0xd2, 0x97, 0xe8, 0xa4, 0x9c, 0x49, 0x46, 0xea, 0x31, 0x73, 0xf0, 0x2d, 0x52, 0x29, 0x91,
	0x3b, 0xc9, 0xb4, 0xfd, 0x5f, 0x30, 0x89, 0x91, 0xca, 0x41, 0x81, 0x25, 0x53, 0x43, 0x6c, 0x37,
	0x23, 0x16, 0x31, 0xfd, 0x1c, 0xa8, 0x57, 0x8e, 0x76, 0x22, 0xc6, 0xa2, 0x09, 0x0e, 0xb4, 0x75,
	0x9e, 0x8d, 0x07, 0x61, 0xc6, 0x7d, 0x19, 0x33, 0x6a, 0xfe, 0x7b, 0xbf, 0x2c, 0xd8, 0x1a, 0x99,
	0xb0, 0x67, 0x2a, 0x2a, 0x69, 0x42, 0x39, 0xa6, 0x21, 0xbe, 0x6b, 0x59, 0x5d, 0xab, 0x6f, 0xbb,
	0xc6, 0x20, 0x07, 0x00, 0xd4, 0x4f, 0x50, 0xa4, 0x7e, 0x80, 0xa2, 0x55, 0xea, 0xae, 0xf7, 0x6b,
	0xfb, 0x5d, 0x67, 0x39, 0x35, 0x27, 0xd7, 0x39, 0x2d, 0x88, 0xee, 0x82, 0x0f, 0x19, 0xc1, 0x36,
	0x4b, 0x91, 0x7a, 0x02, 0xa3, 0x04, 0xa9, 0x14, 0xad, 0x75, 0x2d, 0xd2, 0x59, 0x21, 0x72, 0x66,
	0x68, 0xee, 0x96, 0x72, 0xca, 0x0d, 0x41, 0x0e, 0xa1, 0x11, 0x4c, 0x98, 0xc0, 0x70, 0x2e, 0x63,
	0xdf, 0x4a, 0xa6, 0x6e, 0xdc, 0x0a, 0xa1, 0xde, 0x27, 0x0b, 0x76, 0xae, 0xa7, 0x4b, 0x08, 0xd8,
	0x2a, 0x61, 0x5d, 0x79, 0xd5, 0xd5, 0x6f, 0xf2, 0x18, 0x36, 0x24, 0x4b, 0xe3, 0xa0, 0x28, 0xfa,
	0xce, 0x8a, 0x40, 0x2f, 0x14, 0xc9, 0xcd, 0xb9, 0xe4, 0x04, 0x1a, 0x01, 0xa3, 0x22, 0x4b, 0x90,
	0x7b, 0x11, 0x67, 0x59, 0x5a, 0x94, 0xbb, 0xb7, 0xc2, 0x7d, 0x94, 0xb3, 0x0f, 0x15, 0xd9, 0xad,
	0x07, 0x8b, 0xa6, 0xe8, 0x7d, 0x98, 0x0f, 0x49, 0xc7, 0xb9, 0x31, 0x53, 0x02, 0xb6, 0x9c, 0xa5,
	0xd8, 0x2a, 0x19, 0x4c, 0xbd, 0xc9, 0xbf, 0xb0, 0x21, 0x5e, 0xfb, 0x3c, 0x54, 0xe1, 0xad, 0xfe,
	0xb6, 0x9b, 0x5b, 0xe4, 0x09, 0x54, 0x39, 0x4a, 0xa4, 0x6a, 0x11, 0x5a, 0x76, 0xd7, 0xea, 0xd7,
	0xf6, 0xff, 0x77, 0xcc, 0xa6, 0x38, 0xc5, 0xa6, 0x38, 0x4f, 0xf3, 0x4d, 0x19, 0x6e, 0x5e, 0x7c,
	0xdb, 0x5d, 0xfb, 0xf8, 0x7d, 0xd7, 0x72, 0xe7, 0x5e, 0xbd, 0xaf, 0x16, 0x34, 0x6f, 0x4a, 0xfe,
	0xc6, 0xdc, 0x8e, 0x60, 0xf3, 0x3c, 0xa6, 0x61, 0x4c, 0xa3, 0xa2, 0x8f, 0x0f, 0x6f, 0xd3, 0x08,
	0x67, 0x68, 0x9c, 0xdc, 0x2b, 0xef, 0x55, 0x15, 0xb5, 0x8f, 0xa1, 0x92, 0x93, 0xc9, 0x5d, 0x00,
	0x3d, 0x06, 0x6f, 0x21, 0x8d, 0xaa, 0x46, 0xd4, 0xa8, 0xc9, 0x2e, 0xd4, 0x38, 0xcb, 0x64, 0x4c,
	0x23, 0xef, 0x0d, 0xce, 0xf2, 0x76, 0x41, 0x0e, 0x3d, 0xc3, 0x59, 0xef, 0x73, 0x09, 0xea, 0xcb,
	0xeb, 0x43, 0x1e, 0x40, 0x63, 0x2e, 0xa9, 0x97, 0x25, 0xd7, 0xad, 0x5f, 0xe9, 0x9a, 0x15, 0x5a,
	0x8e, 0x5d, 0xba, 0x1e, 0xbb, 0x0f, 0x3b, 0xe3, 0x98, 0x0b, 0xe9, 0x25, 0x28, 0x84, 0x1f, 0xa1,
	0x17, 0x87, 0xba, 0x8e, 0x2d, 0xb7, 0xae, 0xf1, 0x13, 0x03, 0x1f, 0x87, 0xe4, 0x3e, 0x34, 0x26,
	0xfe, 0x32, 0xd1, 0xd6, 0xc4, 0x6d, 0x05, 0xcf, 0x79, 0x07, 0x50, 0xa6, 0x2c, 0x44, 0xd1, 0x2a,
	0xeb, 0x29, 0xee, 0xfd, 0xfd, 0x0e, 0x9c, 0x53, 0xc5, 0x1d, 0xda, 0x6a, 0xa0, 0xae, 0x71, 0x6c,
	0xbf, 0x84, 0xb2, 0x46, 0x49, 0x0b, 0x2a, 0x29, 0x8f, 0x13, 0x9f, 0xcf, 0xf2, 0xdb, 0x2f, 0x4c,
	0xd2, 0x85, 0x1a, 0xc7, 0x74, 0x12, 0x07, 0xbe, 0xea, 0x91, 0x9e, 0xa0, 0xed, 0x2e, 0x42, 0x6a,
	0xe8, 0x21, 0xa3, 0xa8, 0xb7, 0xdc, 0x76, 0xf5, 0xbb, 0x37, 0x86, 0xca, 0x88, 0x25, 0x89, 0x4f,
	0x43, 0xf2, 0x5c, 0xdf, 0xc3, 0x38, 0x8e, 0x32, 0x8e, 0x9e, 0x6e, 0x87, 0x0e, 0x51, 0xdb, 0xbf,
	0xf7, 0x47, 0xbe, 0x05, 0xcd, 0x1c, 0x14, 0x4e, 0x33, 0x14, 0xf2, 0x68, 0x4d, 0x9f, 0xc4, 0xc2,
	0xc7, 0xb0, 0x0a, 0x95, 0xc0, 0x88, 0x0f, 0x9b, 0x17, 0x97, 0x1d, 0xeb, 0xcb, 0x65, 0xc7, 0xfa,
	0x71, 0xd9, 0xb1, 0xde, 0xff, 0xec, 0xac, 0xbd, 0x2a, 0x25, 0xd3, 0xf3, 0x0d, 0xbd, 0xc7, 0x8f,
	0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x59, 0x18, 0x43, 0x55, 0x05, 0x00, 0x00,
}
