// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cluster_state.proto

package mq

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import client "eventter.io/mq/client"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

import time "time"

import github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ClusterState struct {
	Index                uint64              `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CurrentSegmentID     uint64              `protobuf:"varint,2,opt,name=current_segment_id,json=currentSegmentId,proto3" json:"current_segment_id,omitempty"`
	Namespaces           []*ClusterNamespace `protobuf:"bytes,3,rep,name=namespaces" json:"namespaces,omitempty"`
	OpenSegments         []*ClusterSegment   `protobuf:"bytes,4,rep,name=open_segments,json=openSegments" json:"open_segments,omitempty"`
	ClosedSegments       []*ClusterSegment   `protobuf:"bytes,5,rep,name=closed_segments,json=closedSegments" json:"closed_segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ClusterState) Reset()         { *m = ClusterState{} }
func (m *ClusterState) String() string { return proto.CompactTextString(m) }
func (*ClusterState) ProtoMessage()    {}
func (*ClusterState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{0}
}
func (m *ClusterState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterState.Merge(dst, src)
}
func (m *ClusterState) XXX_Size() int {
	return m.Size()
}
func (m *ClusterState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterState.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterState proto.InternalMessageInfo

func (m *ClusterState) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ClusterState) GetCurrentSegmentID() uint64 {
	if m != nil {
		return m.CurrentSegmentID
	}
	return 0
}

func (m *ClusterState) GetNamespaces() []*ClusterNamespace {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *ClusterState) GetOpenSegments() []*ClusterSegment {
	if m != nil {
		return m.OpenSegments
	}
	return nil
}

func (m *ClusterState) GetClosedSegments() []*ClusterSegment {
	if m != nil {
		return m.ClosedSegments
	}
	return nil
}

type ClusterNamespace struct {
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Topics               []*ClusterTopic         `protobuf:"bytes,2,rep,name=topics" json:"topics,omitempty"`
	ConsumerGroups       []*ClusterConsumerGroup `protobuf:"bytes,3,rep,name=consumer_groups,json=consumerGroups" json:"consumer_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ClusterNamespace) Reset()         { *m = ClusterNamespace{} }
func (m *ClusterNamespace) String() string { return proto.CompactTextString(m) }
func (*ClusterNamespace) ProtoMessage()    {}
func (*ClusterNamespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{1}
}
func (m *ClusterNamespace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterNamespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterNamespace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterNamespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterNamespace.Merge(dst, src)
}
func (m *ClusterNamespace) XXX_Size() int {
	return m.Size()
}
func (m *ClusterNamespace) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterNamespace.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterNamespace proto.InternalMessageInfo

func (m *ClusterNamespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterNamespace) GetTopics() []*ClusterTopic {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *ClusterNamespace) GetConsumerGroups() []*ClusterConsumerGroup {
	if m != nil {
		return m.ConsumerGroups
	}
	return nil
}

type ClusterTopic struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string        `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Shards               uint32        `protobuf:"varint,3,opt,name=shards,proto3" json:"shards,omitempty"`
	ReplicationFactor    uint32        `protobuf:"varint,4,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	Retention            time.Duration `protobuf:"bytes,5,opt,name=retention,stdduration" json:"retention"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClusterTopic) Reset()         { *m = ClusterTopic{} }
func (m *ClusterTopic) String() string { return proto.CompactTextString(m) }
func (*ClusterTopic) ProtoMessage()    {}
func (*ClusterTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{2}
}
func (m *ClusterTopic) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterTopic.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterTopic.Merge(dst, src)
}
func (m *ClusterTopic) XXX_Size() int {
	return m.Size()
}
func (m *ClusterTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterTopic.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterTopic proto.InternalMessageInfo

func (m *ClusterTopic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterTopic) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ClusterTopic) GetShards() uint32 {
	if m != nil {
		return m.Shards
	}
	return 0
}

func (m *ClusterTopic) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

func (m *ClusterTopic) GetRetention() time.Duration {
	if m != nil {
		return m.Retention
	}
	return 0
}

type ClusterConsumerGroup struct {
	Name                 string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bindings             []*ClusterConsumerGroup_Binding `protobuf:"bytes,2,rep,name=bindings" json:"bindings,omitempty"`
	Shards               uint32                          `protobuf:"varint,3,opt,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ClusterConsumerGroup) Reset()         { *m = ClusterConsumerGroup{} }
func (m *ClusterConsumerGroup) String() string { return proto.CompactTextString(m) }
func (*ClusterConsumerGroup) ProtoMessage()    {}
func (*ClusterConsumerGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{3}
}
func (m *ClusterConsumerGroup) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterConsumerGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterConsumerGroup.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterConsumerGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterConsumerGroup.Merge(dst, src)
}
func (m *ClusterConsumerGroup) XXX_Size() int {
	return m.Size()
}
func (m *ClusterConsumerGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterConsumerGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterConsumerGroup proto.InternalMessageInfo

func (m *ClusterConsumerGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterConsumerGroup) GetBindings() []*ClusterConsumerGroup_Binding {
	if m != nil {
		return m.Bindings
	}
	return nil
}

func (m *ClusterConsumerGroup) GetShards() uint32 {
	if m != nil {
		return m.Shards
	}
	return 0
}

type ClusterConsumerGroup_Binding struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	RoutingKey           string   `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterConsumerGroup_Binding) Reset()         { *m = ClusterConsumerGroup_Binding{} }
func (m *ClusterConsumerGroup_Binding) String() string { return proto.CompactTextString(m) }
func (*ClusterConsumerGroup_Binding) ProtoMessage()    {}
func (*ClusterConsumerGroup_Binding) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{3, 0}
}
func (m *ClusterConsumerGroup_Binding) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterConsumerGroup_Binding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterConsumerGroup_Binding.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterConsumerGroup_Binding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterConsumerGroup_Binding.Merge(dst, src)
}
func (m *ClusterConsumerGroup_Binding) XXX_Size() int {
	return m.Size()
}
func (m *ClusterConsumerGroup_Binding) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterConsumerGroup_Binding.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterConsumerGroup_Binding proto.InternalMessageInfo

func (m *ClusterConsumerGroup_Binding) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ClusterConsumerGroup_Binding) GetRoutingKey() string {
	if m != nil {
		return m.RoutingKey
	}
	return ""
}

type ClusterSegment struct {
	ID                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                client.NamespaceName `protobuf:"bytes,2,opt,name=topic" json:"topic"`
	FirstMessageID       []byte               `protobuf:"bytes,3,opt,name=first_message_id,json=firstMessageId,proto3" json:"first_message_id,omitempty"`
	LastMessageID        []byte               `protobuf:"bytes,4,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	Nodes                ClusterSegment_Nodes `protobuf:"bytes,5,opt,name=nodes" json:"nodes"`
	Size_                uint64               `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Sha1                 []byte               `protobuf:"bytes,7,opt,name=sha1,proto3" json:"sha1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ClusterSegment) Reset()         { *m = ClusterSegment{} }
func (m *ClusterSegment) String() string { return proto.CompactTextString(m) }
func (*ClusterSegment) ProtoMessage()    {}
func (*ClusterSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{4}
}
func (m *ClusterSegment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterSegment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterSegment.Merge(dst, src)
}
func (m *ClusterSegment) XXX_Size() int {
	return m.Size()
}
func (m *ClusterSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterSegment.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterSegment proto.InternalMessageInfo

func (m *ClusterSegment) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ClusterSegment) GetTopic() client.NamespaceName {
	if m != nil {
		return m.Topic
	}
	return client.NamespaceName{}
}

func (m *ClusterSegment) GetFirstMessageID() []byte {
	if m != nil {
		return m.FirstMessageID
	}
	return nil
}

func (m *ClusterSegment) GetLastMessageID() []byte {
	if m != nil {
		return m.LastMessageID
	}
	return nil
}

func (m *ClusterSegment) GetNodes() ClusterSegment_Nodes {
	if m != nil {
		return m.Nodes
	}
	return ClusterSegment_Nodes{}
}

func (m *ClusterSegment) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *ClusterSegment) GetSha1() []byte {
	if m != nil {
		return m.Sha1
	}
	return nil
}

type ClusterSegment_Nodes struct {
	PrimaryNodeID        uint64   `protobuf:"varint,1,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"`
	ReplicatingNodeIDs   []uint64 `protobuf:"varint,2,rep,packed,name=replicating_node_ids,json=replicatingNodeIds" json:"replicating_node_ids,omitempty"`
	DoneNodeIDs          []uint64 `protobuf:"varint,3,rep,packed,name=done_node_ids,json=doneNodeIds" json:"done_node_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterSegment_Nodes) Reset()         { *m = ClusterSegment_Nodes{} }
func (m *ClusterSegment_Nodes) String() string { return proto.CompactTextString(m) }
func (*ClusterSegment_Nodes) ProtoMessage()    {}
func (*ClusterSegment_Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{4, 0}
}
func (m *ClusterSegment_Nodes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClusterSegment_Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClusterSegment_Nodes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ClusterSegment_Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterSegment_Nodes.Merge(dst, src)
}
func (m *ClusterSegment_Nodes) XXX_Size() int {
	return m.Size()
}
func (m *ClusterSegment_Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterSegment_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterSegment_Nodes proto.InternalMessageInfo

func (m *ClusterSegment_Nodes) GetPrimaryNodeID() uint64 {
	if m != nil {
		return m.PrimaryNodeID
	}
	return 0
}

func (m *ClusterSegment_Nodes) GetReplicatingNodeIDs() []uint64 {
	if m != nil {
		return m.ReplicatingNodeIDs
	}
	return nil
}

func (m *ClusterSegment_Nodes) GetDoneNodeIDs() []uint64 {
	if m != nil {
		return m.DoneNodeIDs
	}
	return nil
}

type OpenSegmentCommand struct {
	ID                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                client.NamespaceName `protobuf:"bytes,2,opt,name=topic" json:"topic"`
	FirstMessageID       []byte               `protobuf:"bytes,3,opt,name=first_message_id,json=firstMessageId,proto3" json:"first_message_id,omitempty"`
	PrimaryNodeID        uint64               `protobuf:"varint,4,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OpenSegmentCommand) Reset()         { *m = OpenSegmentCommand{} }
func (m *OpenSegmentCommand) String() string { return proto.CompactTextString(m) }
func (*OpenSegmentCommand) ProtoMessage()    {}
func (*OpenSegmentCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{5}
}
func (m *OpenSegmentCommand) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OpenSegmentCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OpenSegmentCommand.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *OpenSegmentCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSegmentCommand.Merge(dst, src)
}
func (m *OpenSegmentCommand) XXX_Size() int {
	return m.Size()
}
func (m *OpenSegmentCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSegmentCommand.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSegmentCommand proto.InternalMessageInfo

func (m *OpenSegmentCommand) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *OpenSegmentCommand) GetTopic() client.NamespaceName {
	if m != nil {
		return m.Topic
	}
	return client.NamespaceName{}
}

func (m *OpenSegmentCommand) GetFirstMessageID() []byte {
	if m != nil {
		return m.FirstMessageID
	}
	return nil
}

func (m *OpenSegmentCommand) GetPrimaryNodeID() uint64 {
	if m != nil {
		return m.PrimaryNodeID
	}
	return 0
}

type CloseSegmentCommand struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DoneNodeID           uint64   `protobuf:"varint,2,opt,name=done_node_id,json=doneNodeId,proto3" json:"done_node_id,omitempty"`
	LastMessageID        []byte   `protobuf:"bytes,4,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	Size_                uint64   `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Sha1                 []byte   `protobuf:"bytes,6,opt,name=sha1,proto3" json:"sha1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSegmentCommand) Reset()         { *m = CloseSegmentCommand{} }
func (m *CloseSegmentCommand) String() string { return proto.CompactTextString(m) }
func (*CloseSegmentCommand) ProtoMessage()    {}
func (*CloseSegmentCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{6}
}
func (m *CloseSegmentCommand) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CloseSegmentCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CloseSegmentCommand.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CloseSegmentCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSegmentCommand.Merge(dst, src)
}
func (m *CloseSegmentCommand) XXX_Size() int {
	return m.Size()
}
func (m *CloseSegmentCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSegmentCommand.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSegmentCommand proto.InternalMessageInfo

func (m *CloseSegmentCommand) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *CloseSegmentCommand) GetDoneNodeID() uint64 {
	if m != nil {
		return m.DoneNodeID
	}
	return 0
}

func (m *CloseSegmentCommand) GetLastMessageID() []byte {
	if m != nil {
		return m.LastMessageID
	}
	return nil
}

func (m *CloseSegmentCommand) GetSize_() uint64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *CloseSegmentCommand) GetSha1() []byte {
	if m != nil {
		return m.Sha1
	}
	return nil
}

type Command struct {
	// Types that are valid to be assigned to Command:
	//	*Command_ConfigureTopic
	//	*Command_DeleteTopic
	//	*Command_ConfigureConsumerGroup
	//	*Command_DeleteConsumerGroup
	//	*Command_OpenSegment
	//	*Command_CloseSegment
	Command              isCommand_Command `protobuf_oneof:"command"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_cluster_state_617466e910bbddf1, []int{7}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Command.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return m.Size()
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

type isCommand_Command interface {
	isCommand_Command()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Command_ConfigureTopic struct {
	ConfigureTopic *client.ConfigureTopicRequest `protobuf:"bytes,1,opt,name=configure_topic,json=configureTopic,oneof"`
}
type Command_DeleteTopic struct {
	DeleteTopic *client.DeleteTopicRequest `protobuf:"bytes,2,opt,name=delete_topic,json=deleteTopic,oneof"`
}
type Command_ConfigureConsumerGroup struct {
	ConfigureConsumerGroup *client.ConfigureConsumerGroupRequest `protobuf:"bytes,3,opt,name=configure_consumer_group,json=configureConsumerGroup,oneof"`
}
type Command_DeleteConsumerGroup struct {
	DeleteConsumerGroup *client.DeleteConsumerGroupRequest `protobuf:"bytes,4,opt,name=delete_consumer_group,json=deleteConsumerGroup,oneof"`
}
type Command_OpenSegment struct {
	OpenSegment *OpenSegmentCommand `protobuf:"bytes,5,opt,name=open_segment,json=openSegment,oneof"`
}
type Command_CloseSegment struct {
	CloseSegment *CloseSegmentCommand `protobuf:"bytes,6,opt,name=close_segment,json=closeSegment,oneof"`
}

func (*Command_ConfigureTopic) isCommand_Command()         {}
func (*Command_DeleteTopic) isCommand_Command()            {}
func (*Command_ConfigureConsumerGroup) isCommand_Command() {}
func (*Command_DeleteConsumerGroup) isCommand_Command()    {}
func (*Command_OpenSegment) isCommand_Command()            {}
func (*Command_CloseSegment) isCommand_Command()           {}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Command) GetConfigureTopic() *client.ConfigureTopicRequest {
	if x, ok := m.GetCommand().(*Command_ConfigureTopic); ok {
		return x.ConfigureTopic
	}
	return nil
}

func (m *Command) GetDeleteTopic() *client.DeleteTopicRequest {
	if x, ok := m.GetCommand().(*Command_DeleteTopic); ok {
		return x.DeleteTopic
	}
	return nil
}

func (m *Command) GetConfigureConsumerGroup() *client.ConfigureConsumerGroupRequest {
	if x, ok := m.GetCommand().(*Command_ConfigureConsumerGroup); ok {
		return x.ConfigureConsumerGroup
	}
	return nil
}

func (m *Command) GetDeleteConsumerGroup() *client.DeleteConsumerGroupRequest {
	if x, ok := m.GetCommand().(*Command_DeleteConsumerGroup); ok {
		return x.DeleteConsumerGroup
	}
	return nil
}

func (m *Command) GetOpenSegment() *OpenSegmentCommand {
	if x, ok := m.GetCommand().(*Command_OpenSegment); ok {
		return x.OpenSegment
	}
	return nil
}

func (m *Command) GetCloseSegment() *CloseSegmentCommand {
	if x, ok := m.GetCommand().(*Command_CloseSegment); ok {
		return x.CloseSegment
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Command) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Command_OneofMarshaler, _Command_OneofUnmarshaler, _Command_OneofSizer, []interface{}{
		(*Command_ConfigureTopic)(nil),
		(*Command_DeleteTopic)(nil),
		(*Command_ConfigureConsumerGroup)(nil),
		(*Command_DeleteConsumerGroup)(nil),
		(*Command_OpenSegment)(nil),
		(*Command_CloseSegment)(nil),
	}
}

func _Command_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Command)
	// command
	switch x := m.Command.(type) {
	case *Command_ConfigureTopic:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConfigureTopic); err != nil {
			return err
		}
	case *Command_DeleteTopic:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeleteTopic); err != nil {
			return err
		}
	case *Command_ConfigureConsumerGroup:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ConfigureConsumerGroup); err != nil {
			return err
		}
	case *Command_DeleteConsumerGroup:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeleteConsumerGroup); err != nil {
			return err
		}
	case *Command_OpenSegment:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OpenSegment); err != nil {
			return err
		}
	case *Command_CloseSegment:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CloseSegment); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Command.Command has unexpected type %T", x)
	}
	return nil
}

func _Command_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Command)
	switch tag {
	case 1: // command.configure_topic
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(client.ConfigureTopicRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Command_ConfigureTopic{msg}
		return true, err
	case 2: // command.delete_topic
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(client.DeleteTopicRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Command_DeleteTopic{msg}
		return true, err
	case 3: // command.configure_consumer_group
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(client.ConfigureConsumerGroupRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Command_ConfigureConsumerGroup{msg}
		return true, err
	case 4: // command.delete_consumer_group
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(client.DeleteConsumerGroupRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Command_DeleteConsumerGroup{msg}
		return true, err
	case 5: // command.open_segment
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OpenSegmentCommand)
		err := b.DecodeMessage(msg)
		m.Command = &Command_OpenSegment{msg}
		return true, err
	case 6: // command.close_segment
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CloseSegmentCommand)
		err := b.DecodeMessage(msg)
		m.Command = &Command_CloseSegment{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Command_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Command)
	// command
	switch x := m.Command.(type) {
	case *Command_ConfigureTopic:
		s := proto.Size(x.ConfigureTopic)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_DeleteTopic:
		s := proto.Size(x.DeleteTopic)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_ConfigureConsumerGroup:
		s := proto.Size(x.ConfigureConsumerGroup)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_DeleteConsumerGroup:
		s := proto.Size(x.DeleteConsumerGroup)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_OpenSegment:
		s := proto.Size(x.OpenSegment)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Command_CloseSegment:
		s := proto.Size(x.CloseSegment)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*ClusterState)(nil), "io.eventter.mq.ClusterState")
	proto.RegisterType((*ClusterNamespace)(nil), "io.eventter.mq.ClusterNamespace")
	proto.RegisterType((*ClusterTopic)(nil), "io.eventter.mq.ClusterTopic")
	proto.RegisterType((*ClusterConsumerGroup)(nil), "io.eventter.mq.ClusterConsumerGroup")
	proto.RegisterType((*ClusterConsumerGroup_Binding)(nil), "io.eventter.mq.ClusterConsumerGroup.Binding")
	proto.RegisterType((*ClusterSegment)(nil), "io.eventter.mq.ClusterSegment")
	proto.RegisterType((*ClusterSegment_Nodes)(nil), "io.eventter.mq.ClusterSegment.Nodes")
	proto.RegisterType((*OpenSegmentCommand)(nil), "io.eventter.mq.OpenSegmentCommand")
	proto.RegisterType((*CloseSegmentCommand)(nil), "io.eventter.mq.CloseSegmentCommand")
	proto.RegisterType((*Command)(nil), "io.eventter.mq.Command")
}
func (m *ClusterState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterState) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Index))
	}
	if m.CurrentSegmentID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.CurrentSegmentID))
	}
	if len(m.Namespaces) > 0 {
		for _, msg := range m.Namespaces {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.OpenSegments) > 0 {
		for _, msg := range m.OpenSegments {
			dAtA[i] = 0x22
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ClosedSegments) > 0 {
		for _, msg := range m.ClosedSegments {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ClusterNamespace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterNamespace) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Topics) > 0 {
		for _, msg := range m.Topics {
			dAtA[i] = 0x12
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ConsumerGroups) > 0 {
		for _, msg := range m.ConsumerGroups {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ClusterTopic) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterTopic) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if m.Shards != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Shards))
	}
	if m.ReplicationFactor != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.ReplicationFactor))
	}
	dAtA[i] = 0x2a
	i++
	i = encodeVarintClusterState(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdDuration(m.Retention)))
	n1, err := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.Retention, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	return i, nil
}

func (m *ClusterConsumerGroup) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterConsumerGroup) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Bindings) > 0 {
		for _, msg := range m.Bindings {
			dAtA[i] = 0x12
			i++
			i = encodeVarintClusterState(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Shards != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Shards))
	}
	return i, nil
}

func (m *ClusterConsumerGroup_Binding) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterConsumerGroup_Binding) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TopicName) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.TopicName)))
		i += copy(dAtA[i:], m.TopicName)
	}
	if len(m.RoutingKey) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.RoutingKey)))
		i += copy(dAtA[i:], m.RoutingKey)
	}
	return i, nil
}

func (m *ClusterSegment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterSegment) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.ID))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintClusterState(dAtA, i, uint64(m.Topic.Size()))
	n2, err := m.Topic.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.FirstMessageID) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.FirstMessageID)))
		i += copy(dAtA[i:], m.FirstMessageID)
	}
	if len(m.LastMessageID) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.LastMessageID)))
		i += copy(dAtA[i:], m.LastMessageID)
	}
	dAtA[i] = 0x2a
	i++
	i = encodeVarintClusterState(dAtA, i, uint64(m.Nodes.Size()))
	n3, err := m.Nodes.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if m.Size_ != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Size_))
	}
	if len(m.Sha1) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Sha1)))
		i += copy(dAtA[i:], m.Sha1)
	}
	return i, nil
}

func (m *ClusterSegment_Nodes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterSegment_Nodes) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.PrimaryNodeID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.PrimaryNodeID))
	}
	if len(m.ReplicatingNodeIDs) > 0 {
		dAtA5 := make([]byte, len(m.ReplicatingNodeIDs)*10)
		var j4 int
		for _, num := range m.ReplicatingNodeIDs {
			for num >= 1<<7 {
				dAtA5[j4] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j4++
			}
			dAtA5[j4] = uint8(num)
			j4++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(j4))
		i += copy(dAtA[i:], dAtA5[:j4])
	}
	if len(m.DoneNodeIDs) > 0 {
		dAtA7 := make([]byte, len(m.DoneNodeIDs)*10)
		var j6 int
		for _, num := range m.DoneNodeIDs {
			for num >= 1<<7 {
				dAtA7[j6] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j6++
			}
			dAtA7[j6] = uint8(num)
			j6++
		}
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(j6))
		i += copy(dAtA[i:], dAtA7[:j6])
	}
	return i, nil
}

func (m *OpenSegmentCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpenSegmentCommand) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.ID))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintClusterState(dAtA, i, uint64(m.Topic.Size()))
	n8, err := m.Topic.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	if len(m.FirstMessageID) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.FirstMessageID)))
		i += copy(dAtA[i:], m.FirstMessageID)
	}
	if m.PrimaryNodeID != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.PrimaryNodeID))
	}
	return i, nil
}

func (m *CloseSegmentCommand) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CloseSegmentCommand) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.ID))
	}
	if m.DoneNodeID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.DoneNodeID))
	}
	if len(m.LastMessageID) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.LastMessageID)))
		i += copy(dAtA[i:], m.LastMessageID)
	}
	if m.Size_ != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.Size_))
	}
	if len(m.Sha1) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(len(m.Sha1)))
		i += copy(dAtA[i:], m.Sha1)
	}
	return i, nil
}

func (m *Command) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Command) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Command != nil {
		nn9, err := m.Command.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn9
	}
	return i, nil
}

func (m *Command_ConfigureTopic) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.ConfigureTopic != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.ConfigureTopic.Size()))
		n10, err := m.ConfigureTopic.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	return i, nil
}
func (m *Command_DeleteTopic) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.DeleteTopic != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.DeleteTopic.Size()))
		n11, err := m.DeleteTopic.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	return i, nil
}
func (m *Command_ConfigureConsumerGroup) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.ConfigureConsumerGroup != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.ConfigureConsumerGroup.Size()))
		n12, err := m.ConfigureConsumerGroup.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	return i, nil
}
func (m *Command_DeleteConsumerGroup) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.DeleteConsumerGroup != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.DeleteConsumerGroup.Size()))
		n13, err := m.DeleteConsumerGroup.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n13
	}
	return i, nil
}
func (m *Command_OpenSegment) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.OpenSegment != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.OpenSegment.Size()))
		n14, err := m.OpenSegment.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n14
	}
	return i, nil
}
func (m *Command_CloseSegment) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CloseSegment != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintClusterState(dAtA, i, uint64(m.CloseSegment.Size()))
		n15, err := m.CloseSegment.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n15
	}
	return i, nil
}
func encodeVarintClusterState(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ClusterState) Size() (n int) {
	var l int
	_ = l
	if m.Index != 0 {
		n += 1 + sovClusterState(uint64(m.Index))
	}
	if m.CurrentSegmentID != 0 {
		n += 1 + sovClusterState(uint64(m.CurrentSegmentID))
	}
	if len(m.Namespaces) > 0 {
		for _, e := range m.Namespaces {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	if len(m.OpenSegments) > 0 {
		for _, e := range m.OpenSegments {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	if len(m.ClosedSegments) > 0 {
		for _, e := range m.ClosedSegments {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	return n
}

func (m *ClusterNamespace) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	if len(m.Topics) > 0 {
		for _, e := range m.Topics {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	if len(m.ConsumerGroups) > 0 {
		for _, e := range m.ConsumerGroups {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	return n
}

func (m *ClusterTopic) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	if m.Shards != 0 {
		n += 1 + sovClusterState(uint64(m.Shards))
	}
	if m.ReplicationFactor != 0 {
		n += 1 + sovClusterState(uint64(m.ReplicationFactor))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.Retention)
	n += 1 + l + sovClusterState(uint64(l))
	return n
}

func (m *ClusterConsumerGroup) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	if len(m.Bindings) > 0 {
		for _, e := range m.Bindings {
			l = e.Size()
			n += 1 + l + sovClusterState(uint64(l))
		}
	}
	if m.Shards != 0 {
		n += 1 + sovClusterState(uint64(m.Shards))
	}
	return n
}

func (m *ClusterConsumerGroup_Binding) Size() (n int) {
	var l int
	_ = l
	l = len(m.TopicName)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = len(m.RoutingKey)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}

func (m *ClusterSegment) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovClusterState(uint64(m.ID))
	}
	l = m.Topic.Size()
	n += 1 + l + sovClusterState(uint64(l))
	l = len(m.FirstMessageID)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = len(m.LastMessageID)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	l = m.Nodes.Size()
	n += 1 + l + sovClusterState(uint64(l))
	if m.Size_ != 0 {
		n += 1 + sovClusterState(uint64(m.Size_))
	}
	l = len(m.Sha1)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}

func (m *ClusterSegment_Nodes) Size() (n int) {
	var l int
	_ = l
	if m.PrimaryNodeID != 0 {
		n += 1 + sovClusterState(uint64(m.PrimaryNodeID))
	}
	if len(m.ReplicatingNodeIDs) > 0 {
		l = 0
		for _, e := range m.ReplicatingNodeIDs {
			l += sovClusterState(uint64(e))
		}
		n += 1 + sovClusterState(uint64(l)) + l
	}
	if len(m.DoneNodeIDs) > 0 {
		l = 0
		for _, e := range m.DoneNodeIDs {
			l += sovClusterState(uint64(e))
		}
		n += 1 + sovClusterState(uint64(l)) + l
	}
	return n
}

func (m *OpenSegmentCommand) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovClusterState(uint64(m.ID))
	}
	l = m.Topic.Size()
	n += 1 + l + sovClusterState(uint64(l))
	l = len(m.FirstMessageID)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	if m.PrimaryNodeID != 0 {
		n += 1 + sovClusterState(uint64(m.PrimaryNodeID))
	}
	return n
}

func (m *CloseSegmentCommand) Size() (n int) {
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovClusterState(uint64(m.ID))
	}
	if m.DoneNodeID != 0 {
		n += 1 + sovClusterState(uint64(m.DoneNodeID))
	}
	l = len(m.LastMessageID)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	if m.Size_ != 0 {
		n += 1 + sovClusterState(uint64(m.Size_))
	}
	l = len(m.Sha1)
	if l > 0 {
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}

func (m *Command) Size() (n int) {
	var l int
	_ = l
	if m.Command != nil {
		n += m.Command.Size()
	}
	return n
}

func (m *Command_ConfigureTopic) Size() (n int) {
	var l int
	_ = l
	if m.ConfigureTopic != nil {
		l = m.ConfigureTopic.Size()
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}
func (m *Command_DeleteTopic) Size() (n int) {
	var l int
	_ = l
	if m.DeleteTopic != nil {
		l = m.DeleteTopic.Size()
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}
func (m *Command_ConfigureConsumerGroup) Size() (n int) {
	var l int
	_ = l
	if m.ConfigureConsumerGroup != nil {
		l = m.ConfigureConsumerGroup.Size()
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}
func (m *Command_DeleteConsumerGroup) Size() (n int) {
	var l int
	_ = l
	if m.DeleteConsumerGroup != nil {
		l = m.DeleteConsumerGroup.Size()
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}
func (m *Command_OpenSegment) Size() (n int) {
	var l int
	_ = l
	if m.OpenSegment != nil {
		l = m.OpenSegment.Size()
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}
func (m *Command_CloseSegment) Size() (n int) {
	var l int
	_ = l
	if m.CloseSegment != nil {
		l = m.CloseSegment.Size()
		n += 1 + l + sovClusterState(uint64(l))
	}
	return n
}

func sovClusterState(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozClusterState(x uint64) (n int) {
	return sovClusterState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClusterState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentSegmentID", wireType)
			}
			m.CurrentSegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentSegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespaces", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespaces = append(m.Namespaces, &ClusterNamespace{})
			if err := m.Namespaces[len(m.Namespaces)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenSegments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OpenSegments = append(m.OpenSegments, &ClusterSegment{})
			if err := m.OpenSegments[len(m.OpenSegments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClosedSegments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClosedSegments = append(m.ClosedSegments, &ClusterSegment{})
			if err := m.ClosedSegments[len(m.ClosedSegments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterNamespace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterNamespace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterNamespace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Topics = append(m.Topics, &ClusterTopic{})
			if err := m.Topics[len(m.Topics)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerGroups", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerGroups = append(m.ConsumerGroups, &ClusterConsumerGroup{})
			if err := m.ConsumerGroups[len(m.ConsumerGroups)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterTopic) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterTopic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterTopic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shards", wireType)
			}
			m.Shards = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Shards |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicationFactor", wireType)
			}
			m.ReplicationFactor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReplicationFactor |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Retention", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.Retention, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterConsumerGroup) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterConsumerGroup: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterConsumerGroup: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bindings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bindings = append(m.Bindings, &ClusterConsumerGroup_Binding{})
			if err := m.Bindings[len(m.Bindings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shards", wireType)
			}
			m.Shards = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Shards |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterConsumerGroup_Binding) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Binding: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Binding: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TopicName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TopicName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoutingKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoutingKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterSegment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterSegment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterSegment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Topic.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstMessageID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstMessageID = append(m.FirstMessageID[:0], dAtA[iNdEx:postIndex]...)
			if m.FirstMessageID == nil {
				m.FirstMessageID = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMessageID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastMessageID = append(m.LastMessageID[:0], dAtA[iNdEx:postIndex]...)
			if m.LastMessageID == nil {
				m.LastMessageID = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Nodes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sha1", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sha1 = append(m.Sha1[:0], dAtA[iNdEx:postIndex]...)
			if m.Sha1 == nil {
				m.Sha1 = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterSegment_Nodes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Nodes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Nodes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrimaryNodeID", wireType)
			}
			m.PrimaryNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrimaryNodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReplicatingNodeIDs = append(m.ReplicatingNodeIDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthClusterState
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowClusterState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReplicatingNodeIDs = append(m.ReplicatingNodeIDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicatingNodeIDs", wireType)
			}
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.DoneNodeIDs = append(m.DoneNodeIDs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthClusterState
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowClusterState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.DoneNodeIDs = append(m.DoneNodeIDs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field DoneNodeIDs", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OpenSegmentCommand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpenSegmentCommand: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpenSegmentCommand: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Topic.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstMessageID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstMessageID = append(m.FirstMessageID[:0], dAtA[iNdEx:postIndex]...)
			if m.FirstMessageID == nil {
				m.FirstMessageID = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrimaryNodeID", wireType)
			}
			m.PrimaryNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrimaryNodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CloseSegmentCommand) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CloseSegmentCommand: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CloseSegmentCommand: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DoneNodeID", wireType)
			}
			m.DoneNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DoneNodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMessageID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastMessageID = append(m.LastMessageID[:0], dAtA[iNdEx:postIndex]...)
			if m.LastMessageID == nil {
				m.LastMessageID = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sha1", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sha1 = append(m.Sha1[:0], dAtA[iNdEx:postIndex]...)
			if m.Sha1 == nil {
				m.Sha1 = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Command) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Command: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Command: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigureTopic", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &client.ConfigureTopicRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Command = &Command_ConfigureTopic{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteTopic", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &client.DeleteTopicRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Command = &Command_DeleteTopic{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigureConsumerGroup", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &client.ConfigureConsumerGroupRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Command = &Command_ConfigureConsumerGroup{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeleteConsumerGroup", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &client.DeleteConsumerGroupRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Command = &Command_DeleteConsumerGroup{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenSegment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &OpenSegmentCommand{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Command = &Command_OpenSegment{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CloseSegment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClusterState
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CloseSegmentCommand{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Command = &Command_CloseSegment{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClusterState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClusterState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClusterState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClusterState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClusterState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthClusterState
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowClusterState
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipClusterState(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthClusterState = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClusterState   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("cluster_state.proto", fileDescriptor_cluster_state_617466e910bbddf1) }

var fileDescriptor_cluster_state_617466e910bbddf1 = []byte{
	// 981 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xae, 0x53, 0x27, 0xdd, 0xbe, 0xf9, 0x68, 0x77, 0x1a, 0x8a, 0xa9, 0xd8, 0xb8, 0x0a, 0x8b,
	0x54, 0x21, 0xd6, 0x85, 0x2e, 0x17, 0x24, 0x0e, 0x8b, 0x13, 0x6d, 0x5b, 0x60, 0x97, 0xd5, 0x2c,
	0x27, 0x2e, 0xc6, 0xf5, 0x4c, 0xbc, 0x16, 0xb1, 0x27, 0x9d, 0x71, 0x10, 0xe5, 0x27, 0x70, 0x82,
	0x1b, 0xff, 0x81, 0x3f, 0xc0, 0x11, 0x38, 0xed, 0x91, 0x1b, 0xb7, 0xb0, 0x32, 0x7f, 0x04, 0xcd,
	0x8c, 0x1d, 0x3b, 0x5f, 0xa8, 0x12, 0x17, 0x4e, 0x99, 0x79, 0x3f, 0x9e, 0xf7, 0x9d, 0xe7, 0x7d,
	0x3c, 0x13, 0x38, 0x08, 0xc6, 0x53, 0x91, 0x52, 0xee, 0x89, 0xd4, 0x4f, 0xa9, 0x33, 0xe1, 0x2c,
	0x65, 0xa8, 0x13, 0x31, 0x87, 0x7e, 0x43, 0x93, 0x34, 0xa5, 0xdc, 0x89, 0xaf, 0x8f, 0x5e, 0x0f,
	0xc6, 0x11, 0x4d, 0xd2, 0xd3, 0xc2, 0x16, 0x5f, 0xeb, 0xc0, 0xa3, 0x6e, 0xc8, 0x42, 0xa6, 0x96,
	0xa7, 0x72, 0x95, 0x5b, 0x7b, 0x21, 0x63, 0xe1, 0x98, 0x9e, 0xaa, 0xdd, 0xd5, 0x74, 0x74, 0x4a,
	0xa6, 0xdc, 0x4f, 0x23, 0x96, 0x68, 0x7f, 0xff, 0x97, 0x1a, 0xb4, 0x06, 0xba, 0xec, 0x73, 0x59,
	0x15, 0x75, 0xa1, 0x1e, 0x25, 0x84, 0x7e, 0x6b, 0x19, 0xc7, 0xc6, 0x89, 0x89, 0xf5, 0x06, 0xb9,
	0x80, 0x82, 0x29, 0xe7, 0x34, 0x49, 0x3d, 0x41, 0xc3, 0x58, 0xfe, 0x46, 0xc4, 0xaa, 0xc9, 0x10,
	0xb7, 0x9b, 0xcd, 0xec, 0xfd, 0x81, 0xf6, 0x3e, 0xd7, 0xce, 0xcb, 0x21, 0xde, 0x0f, 0x16, 0x2d,
	0x04, 0x3d, 0x02, 0x48, 0xfc, 0x98, 0x8a, 0x89, 0x1f, 0x50, 0x61, 0x6d, 0x1f, 0x6f, 0x9f, 0x34,
	0xcf, 0x8e, 0x9d, 0xc5, 0xe3, 0x39, 0x79, 0x2f, 0x4f, 0x8b, 0x40, 0x5c, 0xc9, 0x41, 0x03, 0x68,
	0xb3, 0x09, 0x4d, 0x8a, 0x16, 0x84, 0x65, 0x2a, 0x90, 0xde, 0x06, 0x90, 0xbc, 0x34, 0x6e, 0xc9,
	0xa4, 0x7c, 0x23, 0xd0, 0x39, 0xec, 0x05, 0x63, 0x26, 0x28, 0x29, 0x61, 0xea, 0xb7, 0x82, 0xe9,
	0xe8, 0xb4, 0x02, 0xa8, 0xff, 0xb3, 0x01, 0xfb, 0xcb, 0xed, 0x22, 0x04, 0xa6, 0x6c, 0x58, 0xb1,
	0xb7, 0x8b, 0xd5, 0x1a, 0x7d, 0x00, 0x8d, 0x94, 0x4d, 0xa2, 0x40, 0x58, 0x35, 0x55, 0xe8, 0xcd,
	0x0d, 0x85, 0xbe, 0x90, 0x41, 0x38, 0x8f, 0x45, 0x4f, 0x60, 0x2f, 0x60, 0x89, 0x98, 0xc6, 0x94,
	0x7b, 0x21, 0x67, 0xd3, 0x49, 0xc1, 0xd9, 0xfd, 0x0d, 0xe9, 0x83, 0x3c, 0xfa, 0x5c, 0x06, 0xe3,
	0x4e, 0x50, 0xdd, 0x8a, 0xfe, 0xaf, 0xc6, 0x7c, 0xd0, 0xaa, 0xce, 0xda, 0x4e, 0x11, 0x98, 0xe9,
	0xcd, 0x84, 0xaa, 0xc1, 0xee, 0x62, 0xb5, 0x46, 0x87, 0xd0, 0x10, 0x2f, 0x7c, 0x4e, 0x64, 0x79,
	0xe3, 0xa4, 0x8d, 0xf3, 0x1d, 0x7a, 0x00, 0x88, 0xd3, 0xc9, 0x38, 0x0a, 0x94, 0x9c, 0xbc, 0x91,
	0x1f, 0xa4, 0x8c, 0x5b, 0xa6, 0x8a, 0xb9, 0x5b, 0xf1, 0x3c, 0x56, 0x0e, 0xf4, 0x31, 0xec, 0x72,
	0x9a, 0xd2, 0x44, 0x9a, 0xac, 0xfa, 0xb1, 0x71, 0xd2, 0x3c, 0x7b, 0xc3, 0xd1, 0xe2, 0x74, 0x0a,
	0x71, 0x3a, 0xc3, 0x5c, 0x9c, 0xee, 0x9d, 0x97, 0x33, 0x7b, 0xeb, 0xa7, 0xbf, 0x6c, 0x03, 0x97,
	0x59, 0xfd, 0x3f, 0x0d, 0xe8, 0xae, 0x3b, 0xeb, 0xda, 0xa3, 0x5c, 0xc0, 0x9d, 0xab, 0x28, 0x21,
	0x51, 0x12, 0x16, 0xb4, 0xbf, 0x7b, 0x1b, 0xde, 0x1c, 0x57, 0x27, 0xe1, 0x79, 0xf6, 0x26, 0x02,
	0x8e, 0x2e, 0x61, 0x27, 0x0f, 0x46, 0xf7, 0x00, 0xd4, 0xd4, 0xbc, 0x4a, 0x1b, 0xbb, 0xca, 0x22,
	0x95, 0x81, 0x6c, 0x68, 0x72, 0x36, 0x4d, 0xa3, 0x24, 0xf4, 0xbe, 0xa6, 0x37, 0x39, 0xbb, 0x90,
	0x9b, 0x3e, 0xa5, 0x37, 0xfd, 0xef, 0x4d, 0xe8, 0x2c, 0xaa, 0x0d, 0x1d, 0x42, 0x2d, 0x22, 0xfa,
	0x23, 0x74, 0x1b, 0xd9, 0xcc, 0xae, 0x5d, 0x0e, 0x71, 0x2d, 0x22, 0xe8, 0x43, 0xa8, 0x2b, 0x60,
	0x85, 0xd2, 0x3c, 0xbb, 0xb7, 0x7c, 0xa8, 0xb9, 0x14, 0xe5, 0xc2, 0x35, 0x25, 0x8f, 0x58, 0x67,
	0xa0, 0x8f, 0x60, 0x7f, 0x14, 0x71, 0x91, 0x7a, 0x31, 0x15, 0xc2, 0x0f, 0xa9, 0xfc, 0x84, 0xe5,
	0x91, 0x5a, 0x2e, 0xca, 0x66, 0x76, 0xe7, 0xb1, 0xf4, 0x3d, 0xd1, 0xae, 0xcb, 0x21, 0xee, 0x8c,
	0xaa, 0x7b, 0x59, 0x78, 0x6f, 0xec, 0x2f, 0x26, 0x9b, 0x2a, 0xf9, 0x6e, 0x36, 0xb3, 0xdb, 0x9f,
	0xf9, 0xd5, 0xdc, 0xf6, 0xd8, 0xaf, 0xa6, 0x3e, 0x82, 0x7a, 0xc2, 0x08, 0x15, 0xf9, 0xdc, 0xef,
	0xff, 0xfb, 0x87, 0xe6, 0x3c, 0x95, 0xb1, 0x45, 0xeb, 0x2a, 0x51, 0x4e, 0x58, 0x44, 0xdf, 0x51,
	0xab, 0xa1, 0x2e, 0x25, 0xb5, 0x56, 0xb6, 0x17, 0xfe, 0xfb, 0xd6, 0x8e, 0xec, 0x02, 0xab, 0xf5,
	0xd1, 0x6f, 0x06, 0xd4, 0x55, 0xba, 0x6c, 0x77, 0xc2, 0xa3, 0xd8, 0xe7, 0x37, 0x9e, 0x84, 0xf0,
	0xe6, 0x64, 0xaa, 0x76, 0x9f, 0x69, 0x97, 0x0c, 0x95, 0xed, 0x4e, 0x2a, 0x5b, 0x82, 0x2e, 0xa0,
	0x3b, 0xd7, 0x6f, 0x12, 0x16, 0xe9, 0x5a, 0x46, 0xa6, 0x7b, 0x98, 0xcd, 0x6c, 0x84, 0x4b, 0xbf,
	0xc6, 0x10, 0x18, 0xf1, 0x25, 0x1b, 0x11, 0xe8, 0x21, 0xb4, 0x09, 0x4b, 0x68, 0x09, 0xb1, 0xad,
	0x20, 0xf6, 0xb2, 0x99, 0xdd, 0x1c, 0xb2, 0x84, 0x16, 0xb9, 0x4d, 0x52, 0x6c, 0x88, 0xe8, 0xbf,
	0x32, 0x00, 0x7d, 0x5e, 0xde, 0x58, 0x03, 0x16, 0xc7, 0x7e, 0x42, 0xfe, 0x97, 0x82, 0x58, 0x66,
	0xd8, 0xbc, 0x1d, 0xc3, 0xfd, 0xdf, 0x0d, 0x38, 0x18, 0xc8, 0xdb, 0xf4, 0x96, 0x67, 0x7c, 0x0f,
	0x5a, 0x55, 0x1e, 0xf3, 0x87, 0xa7, 0x93, 0xcd, 0x6c, 0x28, 0x69, 0xc4, 0x50, 0xb2, 0xf8, 0x5f,
	0xd4, 0x5a, 0x68, 0xad, 0xbe, 0x46, 0x6b, 0x8d, 0x52, 0x6b, 0xfd, 0x1f, 0x4d, 0xd8, 0x29, 0x1a,
	0x7f, 0xa6, 0x2e, 0xeb, 0x51, 0x14, 0x4e, 0x39, 0xf5, 0xf4, 0x38, 0x0c, 0x35, 0x8e, 0xb7, 0x57,
	0xb4, 0x5e, 0x84, 0xe9, 0xdb, 0x9e, 0x5e, 0x4f, 0xa9, 0x48, 0x2f, 0xb6, 0xd4, 0x7d, 0x5d, 0x71,
	0xa0, 0x73, 0x68, 0x11, 0x3a, 0xa6, 0x69, 0x01, 0xa7, 0xa7, 0xdb, 0x5f, 0x86, 0x1b, 0xaa, 0x98,
	0x25, 0xac, 0x26, 0x29, 0xad, 0x28, 0x02, 0xab, 0x6c, 0x6d, 0xf1, 0x45, 0x51, 0xc3, 0x6e, 0x9e,
	0x3d, 0xd8, 0xd8, 0xe3, 0xe2, 0x93, 0x32, 0xc7, 0x3f, 0x0c, 0xd6, 0x06, 0xa0, 0xaf, 0xe0, 0xb5,
	0xbc, 0xe7, 0xa5, 0x3a, 0xa6, 0xaa, 0xf3, 0xce, 0xfa, 0xe6, 0x37, 0x14, 0x39, 0x20, 0xab, 0x5e,
	0xc9, 0x4a, 0xf5, 0x1f, 0x40, 0x7e, 0xa1, 0xac, 0xb0, 0xb2, 0xfa, 0xf9, 0x48, 0x56, 0x2a, 0x7f,
	0x03, 0xd0, 0x27, 0xd0, 0x56, 0xcf, 0xf9, 0x1c, 0xa9, 0xa1, 0x90, 0xde, 0x5a, 0xbd, 0x9a, 0x56,
	0x54, 0x7a, 0xb1, 0x85, 0x5b, 0x41, 0xc5, 0xec, 0xee, 0xc2, 0x4e, 0xa0, 0x5d, 0x6e, 0xf7, 0x65,
	0xd6, 0x33, 0xfe, 0xc8, 0x7a, 0xc6, 0xab, 0xac, 0x67, 0xfc, 0xf0, 0x77, 0x6f, 0xeb, 0xcb, 0x5a,
	0x7c, 0x7d, 0xd5, 0x50, 0x0f, 0xdc, 0xc3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x75, 0xda, 0xd4,
	0x1f, 0xe1, 0x09, 0x00, 0x00,
}
