// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: node_rpc.proto

package mq

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import client "eventter.io/mq/client"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DebugRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugRequest) Reset()         { *m = DebugRequest{} }
func (m *DebugRequest) String() string { return proto.CompactTextString(m) }
func (*DebugRequest) ProtoMessage()    {}
func (*DebugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{0}
}
func (m *DebugRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DebugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DebugRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *DebugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugRequest.Merge(dst, src)
}
func (m *DebugRequest) XXX_Size() int {
	return m.Size()
}
func (m *DebugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebugRequest proto.InternalMessageInfo

type DebugResponse struct {
	// Cluster state dumped to string.
	ClusterState string `protobuf:"bytes,1,opt,name=cluster_state,json=clusterState,proto3" json:"cluster_state,omitempty"`
	// Open segments info dumped to string.
	Segments             []string `protobuf:"bytes,2,rep,name=segments" json:"segments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugResponse) Reset()         { *m = DebugResponse{} }
func (m *DebugResponse) String() string { return proto.CompactTextString(m) }
func (*DebugResponse) ProtoMessage()    {}
func (*DebugResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{1}
}
func (m *DebugResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DebugResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DebugResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *DebugResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugResponse.Merge(dst, src)
}
func (m *DebugResponse) XXX_Size() int {
	return m.Size()
}
func (m *DebugResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DebugResponse proto.InternalMessageInfo

func (m *DebugResponse) GetClusterState() string {
	if m != nil {
		return m.ClusterState
	}
	return ""
}

func (m *DebugResponse) GetSegments() []string {
	if m != nil {
		return m.Segments
	}
	return nil
}

type SegmentOpenRequest struct {
	// If true and node is not a leader, request will fail.
	LeaderOnly           bool                 `protobuf:"varint,99,opt,name=leader_only,json=leaderOnly,proto3" json:"leader_only,omitempty"`
	NodeID               uint64               `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Topic                client.NamespaceName `protobuf:"bytes,2,opt,name=topic" json:"topic"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SegmentOpenRequest) Reset()         { *m = SegmentOpenRequest{} }
func (m *SegmentOpenRequest) String() string { return proto.CompactTextString(m) }
func (*SegmentOpenRequest) ProtoMessage()    {}
func (*SegmentOpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{2}
}
func (m *SegmentOpenRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SegmentOpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SegmentOpenRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SegmentOpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentOpenRequest.Merge(dst, src)
}
func (m *SegmentOpenRequest) XXX_Size() int {
	return m.Size()
}
func (m *SegmentOpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentOpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentOpenRequest proto.InternalMessageInfo

func (m *SegmentOpenRequest) GetLeaderOnly() bool {
	if m != nil {
		return m.LeaderOnly
	}
	return false
}

func (m *SegmentOpenRequest) GetNodeID() uint64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *SegmentOpenRequest) GetTopic() client.NamespaceName {
	if m != nil {
		return m.Topic
	}
	return client.NamespaceName{}
}

type SegmentOpenResponse struct {
	SegmentID            uint64   `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	PrimaryNodeID        uint64   `protobuf:"varint,2,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentOpenResponse) Reset()         { *m = SegmentOpenResponse{} }
func (m *SegmentOpenResponse) String() string { return proto.CompactTextString(m) }
func (*SegmentOpenResponse) ProtoMessage()    {}
func (*SegmentOpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{3}
}
func (m *SegmentOpenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SegmentOpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SegmentOpenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SegmentOpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentOpenResponse.Merge(dst, src)
}
func (m *SegmentOpenResponse) XXX_Size() int {
	return m.Size()
}
func (m *SegmentOpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentOpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentOpenResponse proto.InternalMessageInfo

func (m *SegmentOpenResponse) GetSegmentID() uint64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *SegmentOpenResponse) GetPrimaryNodeID() uint64 {
	if m != nil {
		return m.PrimaryNodeID
	}
	return 0
}

type SegmentRotateRequest struct {
	// If true and node is not a leader, request will fail.
	LeaderOnly           bool     `protobuf:"varint,99,opt,name=leader_only,json=leaderOnly,proto3" json:"leader_only,omitempty"`
	NodeID               uint64   `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OldSegmentID         uint64   `protobuf:"varint,2,opt,name=old_segment_id,json=oldSegmentId,proto3" json:"old_segment_id,omitempty"`
	OldSize              int64    `protobuf:"varint,3,opt,name=old_size,json=oldSize,proto3" json:"old_size,omitempty"`
	OldSha1              []byte   `protobuf:"bytes,4,opt,name=old_sha1,json=oldSha1,proto3" json:"old_sha1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentRotateRequest) Reset()         { *m = SegmentRotateRequest{} }
func (m *SegmentRotateRequest) String() string { return proto.CompactTextString(m) }
func (*SegmentRotateRequest) ProtoMessage()    {}
func (*SegmentRotateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{4}
}
func (m *SegmentRotateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SegmentRotateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SegmentRotateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SegmentRotateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentRotateRequest.Merge(dst, src)
}
func (m *SegmentRotateRequest) XXX_Size() int {
	return m.Size()
}
func (m *SegmentRotateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentRotateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentRotateRequest proto.InternalMessageInfo

func (m *SegmentRotateRequest) GetLeaderOnly() bool {
	if m != nil {
		return m.LeaderOnly
	}
	return false
}

func (m *SegmentRotateRequest) GetNodeID() uint64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *SegmentRotateRequest) GetOldSegmentID() uint64 {
	if m != nil {
		return m.OldSegmentID
	}
	return 0
}

func (m *SegmentRotateRequest) GetOldSize() int64 {
	if m != nil {
		return m.OldSize
	}
	return 0
}

func (m *SegmentRotateRequest) GetOldSha1() []byte {
	if m != nil {
		return m.OldSha1
	}
	return nil
}

type SegmentGetSizeRequest struct {
	SegmentID            uint64   `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentGetSizeRequest) Reset()         { *m = SegmentGetSizeRequest{} }
func (m *SegmentGetSizeRequest) String() string { return proto.CompactTextString(m) }
func (*SegmentGetSizeRequest) ProtoMessage()    {}
func (*SegmentGetSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{5}
}
func (m *SegmentGetSizeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SegmentGetSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SegmentGetSizeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SegmentGetSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentGetSizeRequest.Merge(dst, src)
}
func (m *SegmentGetSizeRequest) XXX_Size() int {
	return m.Size()
}
func (m *SegmentGetSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentGetSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentGetSizeRequest proto.InternalMessageInfo

func (m *SegmentGetSizeRequest) GetSegmentID() uint64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

type SegmentGetSizeResponse struct {
	SegmentID            uint64   `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Size_                int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentGetSizeResponse) Reset()         { *m = SegmentGetSizeResponse{} }
func (m *SegmentGetSizeResponse) String() string { return proto.CompactTextString(m) }
func (*SegmentGetSizeResponse) ProtoMessage()    {}
func (*SegmentGetSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{6}
}
func (m *SegmentGetSizeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SegmentGetSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SegmentGetSizeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SegmentGetSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentGetSizeResponse.Merge(dst, src)
}
func (m *SegmentGetSizeResponse) XXX_Size() int {
	return m.Size()
}
func (m *SegmentGetSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentGetSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentGetSizeResponse proto.InternalMessageInfo

func (m *SegmentGetSizeResponse) GetSegmentID() uint64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *SegmentGetSizeResponse) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

type SegmentReadRequest struct {
	SegmentID uint64 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Offset    int64  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// If true, will wait for more messages.
	Wait                 bool     `protobuf:"varint,3,opt,name=wait,proto3" json:"wait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentReadRequest) Reset()         { *m = SegmentReadRequest{} }
func (m *SegmentReadRequest) String() string { return proto.CompactTextString(m) }
func (*SegmentReadRequest) ProtoMessage()    {}
func (*SegmentReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{7}
}
func (m *SegmentReadRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SegmentReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SegmentReadRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SegmentReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentReadRequest.Merge(dst, src)
}
func (m *SegmentReadRequest) XXX_Size() int {
	return m.Size()
}
func (m *SegmentReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentReadRequest proto.InternalMessageInfo

func (m *SegmentReadRequest) GetSegmentID() uint64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *SegmentReadRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SegmentReadRequest) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

type SegmentReadResponse struct {
	SegmentID            uint64   `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentReadResponse) Reset()         { *m = SegmentReadResponse{} }
func (m *SegmentReadResponse) String() string { return proto.CompactTextString(m) }
func (*SegmentReadResponse) ProtoMessage()    {}
func (*SegmentReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_3449127f33feabed, []int{8}
}
func (m *SegmentReadResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SegmentReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SegmentReadResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SegmentReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentReadResponse.Merge(dst, src)
}
func (m *SegmentReadResponse) XXX_Size() int {
	return m.Size()
}
func (m *SegmentReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentReadResponse proto.InternalMessageInfo

func (m *SegmentReadResponse) GetSegmentID() uint64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *SegmentReadResponse) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SegmentReadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DebugRequest)(nil), "io.eventter.mq.DebugRequest")
	proto.RegisterType((*DebugResponse)(nil), "io.eventter.mq.DebugResponse")
	proto.RegisterType((*SegmentOpenRequest)(nil), "io.eventter.mq.SegmentOpenRequest")
	proto.RegisterType((*SegmentOpenResponse)(nil), "io.eventter.mq.SegmentOpenResponse")
	proto.RegisterType((*SegmentRotateRequest)(nil), "io.eventter.mq.SegmentRotateRequest")
	proto.RegisterType((*SegmentGetSizeRequest)(nil), "io.eventter.mq.SegmentGetSizeRequest")
	proto.RegisterType((*SegmentGetSizeResponse)(nil), "io.eventter.mq.SegmentGetSizeResponse")
	proto.RegisterType((*SegmentReadRequest)(nil), "io.eventter.mq.SegmentReadRequest")
	proto.RegisterType((*SegmentReadResponse)(nil), "io.eventter.mq.SegmentReadResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeRPC service

type NodeRPCClient interface {
	Debug(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (*DebugResponse, error)
	SegmentOpen(ctx context.Context, in *SegmentOpenRequest, opts ...grpc.CallOption) (*SegmentOpenResponse, error)
	SegmentRotate(ctx context.Context, in *SegmentRotateRequest, opts ...grpc.CallOption) (*SegmentOpenResponse, error)
	SegmentGetSize(ctx context.Context, in *SegmentGetSizeRequest, opts ...grpc.CallOption) (*SegmentGetSizeResponse, error)
	SegmentRead(ctx context.Context, in *SegmentReadRequest, opts ...grpc.CallOption) (NodeRPC_SegmentReadClient, error)
}

type nodeRPCClient struct {
	cc *grpc.ClientConn
}

func NewNodeRPCClient(cc *grpc.ClientConn) NodeRPCClient {
	return &nodeRPCClient{cc}
}

func (c *nodeRPCClient) Debug(ctx context.Context, in *DebugRequest, opts ...grpc.CallOption) (*DebugResponse, error) {
	out := new(DebugResponse)
	err := c.cc.Invoke(ctx, "/io.eventter.mq.NodeRPC/Debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) SegmentOpen(ctx context.Context, in *SegmentOpenRequest, opts ...grpc.CallOption) (*SegmentOpenResponse, error) {
	out := new(SegmentOpenResponse)
	err := c.cc.Invoke(ctx, "/io.eventter.mq.NodeRPC/SegmentOpen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) SegmentRotate(ctx context.Context, in *SegmentRotateRequest, opts ...grpc.CallOption) (*SegmentOpenResponse, error) {
	out := new(SegmentOpenResponse)
	err := c.cc.Invoke(ctx, "/io.eventter.mq.NodeRPC/SegmentRotate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) SegmentGetSize(ctx context.Context, in *SegmentGetSizeRequest, opts ...grpc.CallOption) (*SegmentGetSizeResponse, error) {
	out := new(SegmentGetSizeResponse)
	err := c.cc.Invoke(ctx, "/io.eventter.mq.NodeRPC/SegmentGetSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) SegmentRead(ctx context.Context, in *SegmentReadRequest, opts ...grpc.CallOption) (NodeRPC_SegmentReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeRPC_serviceDesc.Streams[0], "/io.eventter.mq.NodeRPC/SegmentRead", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeRPCSegmentReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeRPC_SegmentReadClient interface {
	Recv() (*SegmentReadResponse, error)
	grpc.ClientStream
}

type nodeRPCSegmentReadClient struct {
	grpc.ClientStream
}

func (x *nodeRPCSegmentReadClient) Recv() (*SegmentReadResponse, error) {
	m := new(SegmentReadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for NodeRPC service

type NodeRPCServer interface {
	Debug(context.Context, *DebugRequest) (*DebugResponse, error)
	SegmentOpen(context.Context, *SegmentOpenRequest) (*SegmentOpenResponse, error)
	SegmentRotate(context.Context, *SegmentRotateRequest) (*SegmentOpenResponse, error)
	SegmentGetSize(context.Context, *SegmentGetSizeRequest) (*SegmentGetSizeResponse, error)
	SegmentRead(*SegmentReadRequest, NodeRPC_SegmentReadServer) error
}

func RegisterNodeRPCServer(s *grpc.Server, srv NodeRPCServer) {
	s.RegisterService(&_NodeRPC_serviceDesc, srv)
}

func _NodeRPC_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.eventter.mq.NodeRPC/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).Debug(ctx, req.(*DebugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_SegmentOpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentOpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).SegmentOpen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.eventter.mq.NodeRPC/SegmentOpen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).SegmentOpen(ctx, req.(*SegmentOpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_SegmentRotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentRotateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).SegmentRotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.eventter.mq.NodeRPC/SegmentRotate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).SegmentRotate(ctx, req.(*SegmentRotateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_SegmentGetSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SegmentGetSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).SegmentGetSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.eventter.mq.NodeRPC/SegmentGetSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).SegmentGetSize(ctx, req.(*SegmentGetSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_SegmentRead_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SegmentReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeRPCServer).SegmentRead(m, &nodeRPCSegmentReadServer{stream})
}

type NodeRPC_SegmentReadServer interface {
	Send(*SegmentReadResponse) error
	grpc.ServerStream
}

type nodeRPCSegmentReadServer struct {
	grpc.ServerStream
}

func (x *nodeRPCSegmentReadServer) Send(m *SegmentReadResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _NodeRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.eventter.mq.NodeRPC",
	HandlerType: (*NodeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Debug",
			Handler:    _NodeRPC_Debug_Handler,
		},
		{
			MethodName: "SegmentOpen",
			Handler:    _NodeRPC_SegmentOpen_Handler,
		},
		{
			MethodName: "SegmentRotate",
			Handler:    _NodeRPC_SegmentRotate_Handler,
		},
		{
			MethodName: "SegmentGetSize",
			Handler:    _NodeRPC_SegmentGetSize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SegmentRead",
			Handler:       _NodeRPC_SegmentRead_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node_rpc.proto",
}

func (m *DebugRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DebugRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *DebugResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DebugResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ClusterState) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(len(m.ClusterState)))
		i += copy(dAtA[i:], m.ClusterState)
	}
	if len(m.Segments) > 0 {
		for _, s := range m.Segments {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *SegmentOpenRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentOpenRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.NodeID))
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintNodeRpc(dAtA, i, uint64(m.Topic.Size()))
	n1, err := m.Topic.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	if m.LeaderOnly {
		dAtA[i] = 0x98
		i++
		dAtA[i] = 0x6
		i++
		if m.LeaderOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *SegmentOpenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentOpenResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SegmentID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.SegmentID))
	}
	if m.PrimaryNodeID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.PrimaryNodeID))
	}
	return i, nil
}

func (m *SegmentRotateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentRotateRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.NodeID))
	}
	if m.OldSegmentID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.OldSegmentID))
	}
	if m.OldSize != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.OldSize))
	}
	if len(m.OldSha1) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(len(m.OldSha1)))
		i += copy(dAtA[i:], m.OldSha1)
	}
	if m.LeaderOnly {
		dAtA[i] = 0x98
		i++
		dAtA[i] = 0x6
		i++
		if m.LeaderOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *SegmentGetSizeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentGetSizeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SegmentID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.SegmentID))
	}
	return i, nil
}

func (m *SegmentGetSizeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentGetSizeResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SegmentID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.SegmentID))
	}
	if m.Size_ != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.Size_))
	}
	return i, nil
}

func (m *SegmentReadRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentReadRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SegmentID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.SegmentID))
	}
	if m.Offset != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.Offset))
	}
	if m.Wait {
		dAtA[i] = 0x18
		i++
		if m.Wait {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *SegmentReadResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SegmentReadResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SegmentID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.SegmentID))
	}
	if m.Offset != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.Offset))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func encodeVarintNodeRpc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *DebugRequest) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *DebugResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.ClusterState)
	if l > 0 {
		n += 1 + l + sovNodeRpc(uint64(l))
	}
	if len(m.Segments) > 0 {
		for _, s := range m.Segments {
			l = len(s)
			n += 1 + l + sovNodeRpc(uint64(l))
		}
	}
	return n
}

func (m *SegmentOpenRequest) Size() (n int) {
	var l int
	_ = l
	if m.NodeID != 0 {
		n += 1 + sovNodeRpc(uint64(m.NodeID))
	}
	l = m.Topic.Size()
	n += 1 + l + sovNodeRpc(uint64(l))
	if m.LeaderOnly {
		n += 3
	}
	return n
}

func (m *SegmentOpenResponse) Size() (n int) {
	var l int
	_ = l
	if m.SegmentID != 0 {
		n += 1 + sovNodeRpc(uint64(m.SegmentID))
	}
	if m.PrimaryNodeID != 0 {
		n += 1 + sovNodeRpc(uint64(m.PrimaryNodeID))
	}
	return n
}

func (m *SegmentRotateRequest) Size() (n int) {
	var l int
	_ = l
	if m.NodeID != 0 {
		n += 1 + sovNodeRpc(uint64(m.NodeID))
	}
	if m.OldSegmentID != 0 {
		n += 1 + sovNodeRpc(uint64(m.OldSegmentID))
	}
	if m.OldSize != 0 {
		n += 1 + sovNodeRpc(uint64(m.OldSize))
	}
	l = len(m.OldSha1)
	if l > 0 {
		n += 1 + l + sovNodeRpc(uint64(l))
	}
	if m.LeaderOnly {
		n += 3
	}
	return n
}

func (m *SegmentGetSizeRequest) Size() (n int) {
	var l int
	_ = l
	if m.SegmentID != 0 {
		n += 1 + sovNodeRpc(uint64(m.SegmentID))
	}
	return n
}

func (m *SegmentGetSizeResponse) Size() (n int) {
	var l int
	_ = l
	if m.SegmentID != 0 {
		n += 1 + sovNodeRpc(uint64(m.SegmentID))
	}
	if m.Size_ != 0 {
		n += 1 + sovNodeRpc(uint64(m.Size_))
	}
	return n
}

func (m *SegmentReadRequest) Size() (n int) {
	var l int
	_ = l
	if m.SegmentID != 0 {
		n += 1 + sovNodeRpc(uint64(m.SegmentID))
	}
	if m.Offset != 0 {
		n += 1 + sovNodeRpc(uint64(m.Offset))
	}
	if m.Wait {
		n += 2
	}
	return n
}

func (m *SegmentReadResponse) Size() (n int) {
	var l int
	_ = l
	if m.SegmentID != 0 {
		n += 1 + sovNodeRpc(uint64(m.SegmentID))
	}
	if m.Offset != 0 {
		n += 1 + sovNodeRpc(uint64(m.Offset))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovNodeRpc(uint64(l))
	}
	return n
}

func sovNodeRpc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozNodeRpc(x uint64) (n int) {
	return sovNodeRpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DebugRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DebugRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DebugRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DebugResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DebugResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DebugResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterState", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterState = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Segments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Segments = append(m.Segments, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentOpenRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentOpenRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentOpenRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Topic.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 99:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LeaderOnly = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentOpenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentOpenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentOpenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SegmentID", wireType)
			}
			m.SegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrimaryNodeID", wireType)
			}
			m.PrimaryNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrimaryNodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentRotateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentRotateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentRotateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldSegmentID", wireType)
			}
			m.OldSegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldSegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldSize", wireType)
			}
			m.OldSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldSize |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldSha1", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldSha1 = append(m.OldSha1[:0], dAtA[iNdEx:postIndex]...)
			if m.OldSha1 == nil {
				m.OldSha1 = []byte{}
			}
			iNdEx = postIndex
		case 99:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LeaderOnly = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentGetSizeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentGetSizeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentGetSizeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SegmentID", wireType)
			}
			m.SegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentGetSizeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentGetSizeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentGetSizeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SegmentID", wireType)
			}
			m.SegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentReadRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentReadRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentReadRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SegmentID", wireType)
			}
			m.SegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wait", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Wait = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SegmentReadResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SegmentReadResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SegmentReadResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SegmentID", wireType)
			}
			m.SegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNodeRpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthNodeRpc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowNodeRpc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipNodeRpc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthNodeRpc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNodeRpc   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("node_rpc.proto", fileDescriptor_node_rpc_3449127f33feabed) }

var fileDescriptor_node_rpc_3449127f33feabed = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0x26, 0x69, 0x9a, 0x4c, 0x93, 0x00, 0x4b, 0x29, 0x21, 0xa2, 0xb1, 0xe5, 0x02, 0xf2,
	0x01, 0xa5, 0xb4, 0x48, 0x48, 0x5c, 0x4b, 0x10, 0xea, 0xa5, 0xad, 0xb6, 0x12, 0x42, 0xbd, 0x58,
	0xae, 0x3d, 0x4d, 0x2d, 0xd9, 0x5e, 0xc7, 0xde, 0x82, 0xda, 0x03, 0xcf, 0xc0, 0x85, 0xd7, 0xe1,
	0x5c, 0x71, 0xe2, 0x09, 0x22, 0x64, 0x5e, 0x04, 0x79, 0xbd, 0x4d, 0xed, 0xa2, 0xb4, 0x34, 0xb7,
	0x99, 0x9d, 0xbf, 0xef, 0x1b, 0x7f, 0x63, 0xe8, 0x84, 0xdc, 0x45, 0x2b, 0x8e, 0x9c, 0x41, 0x14,
	0x73, 0xc1, 0x69, 0xc7, 0xe3, 0x03, 0xfc, 0x8c, 0xa1, 0x10, 0x18, 0x0f, 0x82, 0x71, 0xef, 0xb1,
	0xe3, 0x7b, 0x18, 0x8a, 0x8d, 0xcb, 0xb7, 0x60, 0x9c, 0x27, 0xf6, 0x56, 0x46, 0x7c, 0xc4, 0xa5,
	0xb9, 0x91, 0x59, 0xf9, 0xab, 0xd1, 0x81, 0xd6, 0x10, 0x8f, 0x4e, 0x47, 0x0c, 0xc7, 0xa7, 0x98,
	0x08, 0x63, 0x1f, 0xda, 0xca, 0x4f, 0x22, 0x1e, 0x26, 0x48, 0xd7, 0xa1, 0xed, 0xf8, 0xa7, 0x89,
	0xc0, 0xd8, 0x4a, 0x84, 0x2d, 0xb0, 0x4b, 0x74, 0x62, 0x36, 0x59, 0x4b, 0x3d, 0x1e, 0x64, 0x6f,
	0xb4, 0x07, 0x8d, 0x04, 0x47, 0x01, 0x86, 0x22, 0xe9, 0x56, 0xf4, 0xaa, 0xd9, 0x64, 0x53, 0xdf,
	0xf8, 0x4e, 0x80, 0x1e, 0xe4, 0xce, 0x5e, 0x84, 0xa1, 0x1a, 0x44, 0xd7, 0x61, 0x49, 0x32, 0xf1,
	0x5c, 0xd9, 0xb1, 0xb6, 0x0d, 0xe9, 0x44, 0xab, 0xef, 0x72, 0x17, 0x77, 0x86, 0xac, 0x9e, 0x85,
	0x76, 0x5c, 0xfa, 0x16, 0x16, 0x05, 0x8f, 0x3c, 0xa7, 0x5b, 0xd1, 0x89, 0xb9, 0xbc, 0xb5, 0x36,
	0x28, 0x93, 0x1d, 0xec, 0xda, 0x01, 0x26, 0x91, 0xed, 0x60, 0x66, 0x6c, 0xd7, 0x2e, 0x26, 0xda,
	0x02, 0xcb, 0x2b, 0xa8, 0x06, 0xcb, 0x3e, 0xda, 0x2e, 0xc6, 0x16, 0x0f, 0xfd, 0xb3, 0xae, 0xa3,
	0x13, 0xb3, 0xc1, 0x20, 0x7f, 0xda, 0x0b, 0xfd, 0x33, 0xe3, 0x2b, 0x3c, 0x2c, 0xc1, 0x52, 0x7c,
	0x5f, 0x02, 0x28, 0xe8, 0x57, 0xd0, 0xda, 0xe9, 0x44, 0x6b, 0xaa, 0xe4, 0x9d, 0x21, 0x6b, 0xaa,
	0x04, 0x09, 0xf0, 0x5e, 0x14, 0x7b, 0x81, 0x1d, 0x9f, 0x59, 0x97, 0x6c, 0x2a, 0xb2, 0xe4, 0x41,
	0x3a, 0xd1, 0xda, 0xfb, 0x79, 0x48, 0x91, 0x6a, 0x47, 0x05, 0xd7, 0x35, 0x7e, 0x12, 0x58, 0x51,
	0x3d, 0x19, 0xcf, 0xb6, 0x78, 0xa7, 0xcd, 0xbc, 0x81, 0x0e, 0xf7, 0x5d, 0xab, 0x00, 0x35, 0x9f,
	0x7b, 0x3f, 0x9d, 0x68, 0xad, 0x3d, 0xdf, 0xbd, 0x42, 0xdb, 0xe2, 0x57, 0x9e, 0x4b, 0x9f, 0x40,
	0x43, 0xd6, 0x79, 0xe7, 0xd8, 0xad, 0xea, 0xc4, 0xac, 0xb2, 0xa5, 0x2c, 0xee, 0x9d, 0xe3, 0x34,
	0x74, 0x62, 0x6f, 0x76, 0x6b, 0x3a, 0x31, 0x5b, 0x79, 0xe8, 0xc4, 0xde, 0xbc, 0x7d, 0x99, 0xef,
	0xe1, 0x91, 0x9a, 0xf1, 0x01, 0x45, 0xd6, 0xed, 0x92, 0xcc, 0x9d, 0xd6, 0x69, 0x1c, 0xc2, 0xea,
	0xf5, 0x36, 0x73, 0x7d, 0x16, 0x0a, 0x35, 0xc9, 0xb0, 0x22, 0x19, 0x4a, 0xdb, 0x08, 0xa7, 0x32,
	0x64, 0x68, 0xbb, 0x73, 0xe1, 0xa3, 0xab, 0x50, 0xe7, 0xc7, 0xc7, 0x09, 0x0a, 0xd5, 0x59, 0x79,
	0xd9, 0xbc, 0x2f, 0xb6, 0x27, 0xe4, 0x46, 0x1b, 0x4c, 0xda, 0x06, 0x9f, 0xea, 0x2b, 0x9f, 0x37,
	0x17, 0x91, 0x1b, 0x06, 0xba, 0xb6, 0xb0, 0xe5, 0xc0, 0x16, 0x93, 0xf6, 0xd6, 0x8f, 0x2a, 0x2c,
	0x65, 0x2a, 0x61, 0xfb, 0xef, 0xe8, 0x10, 0x16, 0xe5, 0x19, 0xd3, 0xa7, 0xd7, 0x4f, 0xa6, 0x78,
	0xed, 0xbd, 0xb5, 0x19, 0x51, 0x85, 0xf5, 0x23, 0x2c, 0x17, 0x4e, 0x84, 0x1a, 0xd7, 0xb3, 0xff,
	0x3d, 0xeb, 0xde, 0xfa, 0x8d, 0x39, 0xaa, 0xef, 0x21, 0xb4, 0x4b, 0xca, 0xa7, 0xcf, 0x66, 0x54,
	0x95, 0x0e, 0xe3, 0xff, 0x7a, 0x5b, 0xd0, 0x29, 0x4b, 0x88, 0x3e, 0x9f, 0x51, 0x56, 0x56, 0x6a,
	0xef, 0xc5, 0x6d, 0x69, 0x6a, 0xc0, 0xa7, 0xe9, 0x52, 0xb2, 0xef, 0x3a, 0x73, 0x29, 0x05, 0x91,
	0xcd, 0x04, 0x5e, 0x14, 0xc6, 0x2b, 0xb2, 0xbd, 0x72, 0x91, 0xf6, 0xc9, 0xaf, 0xb4, 0x4f, 0x7e,
	0xa7, 0x7d, 0xf2, 0xed, 0x4f, 0x7f, 0xe1, 0xb0, 0x12, 0x8c, 0x8f, 0xea, 0xf2, 0x47, 0xfd, 0xfa,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xa1, 0x3c, 0x2f, 0xf9, 0x05, 0x00, 0x00,
}
