// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: node_rpc.proto

package mq

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import client "eventter.io/mq/client"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OpenSegmentRequest struct {
	NodeID               uint64                `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Topic                *client.NamespaceName `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
	FirstMessageID       []byte                `protobuf:"bytes,3,opt,name=first_message_id,json=firstMessageId,proto3" json:"first_message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OpenSegmentRequest) Reset()         { *m = OpenSegmentRequest{} }
func (m *OpenSegmentRequest) String() string { return proto.CompactTextString(m) }
func (*OpenSegmentRequest) ProtoMessage()    {}
func (*OpenSegmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_35e65d3ddca5348d, []int{0}
}
func (m *OpenSegmentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OpenSegmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OpenSegmentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *OpenSegmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSegmentRequest.Merge(dst, src)
}
func (m *OpenSegmentRequest) XXX_Size() int {
	return m.Size()
}
func (m *OpenSegmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSegmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSegmentRequest proto.InternalMessageInfo

func (m *OpenSegmentRequest) GetNodeID() uint64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *OpenSegmentRequest) GetTopic() *client.NamespaceName {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *OpenSegmentRequest) GetFirstMessageID() []byte {
	if m != nil {
		return m.FirstMessageID
	}
	return nil
}

type OpenSegmentResponse struct {
	SegmentID            uint64   `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	PrimaryNodeID        uint64   `protobuf:"varint,2,opt,name=primary_node_id,json=primaryNodeId,proto3" json:"primary_node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenSegmentResponse) Reset()         { *m = OpenSegmentResponse{} }
func (m *OpenSegmentResponse) String() string { return proto.CompactTextString(m) }
func (*OpenSegmentResponse) ProtoMessage()    {}
func (*OpenSegmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_35e65d3ddca5348d, []int{1}
}
func (m *OpenSegmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OpenSegmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OpenSegmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *OpenSegmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenSegmentResponse.Merge(dst, src)
}
func (m *OpenSegmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *OpenSegmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenSegmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenSegmentResponse proto.InternalMessageInfo

func (m *OpenSegmentResponse) GetSegmentID() uint64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *OpenSegmentResponse) GetPrimaryNodeID() uint64 {
	if m != nil {
		return m.PrimaryNodeID
	}
	return 0
}

type RotateSegmentRequest struct {
	NodeID               uint64   `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	OldSegmentID         uint64   `protobuf:"varint,2,opt,name=old_segment_id,json=oldSegmentId,proto3" json:"old_segment_id,omitempty"`
	OldLastMessageID     []byte   `protobuf:"bytes,3,opt,name=old_last_message_id,json=oldLastMessageId,proto3" json:"old_last_message_id,omitempty"`
	OldSize              uint64   `protobuf:"varint,4,opt,name=old_size,json=oldSize,proto3" json:"old_size,omitempty"`
	OldSha1              []byte   `protobuf:"bytes,5,opt,name=old_sha1,json=oldSha1,proto3" json:"old_sha1,omitempty"`
	NewFirstMessageID    []byte   `protobuf:"bytes,6,opt,name=new_first_message_id,json=newFirstMessageId,proto3" json:"new_first_message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RotateSegmentRequest) Reset()         { *m = RotateSegmentRequest{} }
func (m *RotateSegmentRequest) String() string { return proto.CompactTextString(m) }
func (*RotateSegmentRequest) ProtoMessage()    {}
func (*RotateSegmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_rpc_35e65d3ddca5348d, []int{2}
}
func (m *RotateSegmentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RotateSegmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RotateSegmentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RotateSegmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RotateSegmentRequest.Merge(dst, src)
}
func (m *RotateSegmentRequest) XXX_Size() int {
	return m.Size()
}
func (m *RotateSegmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RotateSegmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RotateSegmentRequest proto.InternalMessageInfo

func (m *RotateSegmentRequest) GetNodeID() uint64 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *RotateSegmentRequest) GetOldSegmentID() uint64 {
	if m != nil {
		return m.OldSegmentID
	}
	return 0
}

func (m *RotateSegmentRequest) GetOldLastMessageID() []byte {
	if m != nil {
		return m.OldLastMessageID
	}
	return nil
}

func (m *RotateSegmentRequest) GetOldSize() uint64 {
	if m != nil {
		return m.OldSize
	}
	return 0
}

func (m *RotateSegmentRequest) GetOldSha1() []byte {
	if m != nil {
		return m.OldSha1
	}
	return nil
}

func (m *RotateSegmentRequest) GetNewFirstMessageID() []byte {
	if m != nil {
		return m.NewFirstMessageID
	}
	return nil
}

func init() {
	proto.RegisterType((*OpenSegmentRequest)(nil), "io.eventter.mq.OpenSegmentRequest")
	proto.RegisterType((*OpenSegmentResponse)(nil), "io.eventter.mq.OpenSegmentResponse")
	proto.RegisterType((*RotateSegmentRequest)(nil), "io.eventter.mq.RotateSegmentRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeRPC service

type NodeRPCClient interface {
	OpenSegment(ctx context.Context, in *OpenSegmentRequest, opts ...grpc.CallOption) (*OpenSegmentResponse, error)
	RotateSegment(ctx context.Context, in *RotateSegmentRequest, opts ...grpc.CallOption) (*OpenSegmentResponse, error)
}

type nodeRPCClient struct {
	cc *grpc.ClientConn
}

func NewNodeRPCClient(cc *grpc.ClientConn) NodeRPCClient {
	return &nodeRPCClient{cc}
}

func (c *nodeRPCClient) OpenSegment(ctx context.Context, in *OpenSegmentRequest, opts ...grpc.CallOption) (*OpenSegmentResponse, error) {
	out := new(OpenSegmentResponse)
	err := c.cc.Invoke(ctx, "/io.eventter.mq.NodeRPC/OpenSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeRPCClient) RotateSegment(ctx context.Context, in *RotateSegmentRequest, opts ...grpc.CallOption) (*OpenSegmentResponse, error) {
	out := new(OpenSegmentResponse)
	err := c.cc.Invoke(ctx, "/io.eventter.mq.NodeRPC/RotateSegment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeRPC service

type NodeRPCServer interface {
	OpenSegment(context.Context, *OpenSegmentRequest) (*OpenSegmentResponse, error)
	RotateSegment(context.Context, *RotateSegmentRequest) (*OpenSegmentResponse, error)
}

func RegisterNodeRPCServer(s *grpc.Server, srv NodeRPCServer) {
	s.RegisterService(&_NodeRPC_serviceDesc, srv)
}

func _NodeRPC_OpenSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).OpenSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.eventter.mq.NodeRPC/OpenSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).OpenSegment(ctx, req.(*OpenSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeRPC_RotateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRPCServer).RotateSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.eventter.mq.NodeRPC/RotateSegment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRPCServer).RotateSegment(ctx, req.(*RotateSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.eventter.mq.NodeRPC",
	HandlerType: (*NodeRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenSegment",
			Handler:    _NodeRPC_OpenSegment_Handler,
		},
		{
			MethodName: "RotateSegment",
			Handler:    _NodeRPC_RotateSegment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_rpc.proto",
}

func (m *OpenSegmentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpenSegmentRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.NodeID))
	}
	if m.Topic != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.Topic.Size()))
		n1, err := m.Topic.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.FirstMessageID) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(len(m.FirstMessageID)))
		i += copy(dAtA[i:], m.FirstMessageID)
	}
	return i, nil
}

func (m *OpenSegmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpenSegmentResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.SegmentID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.SegmentID))
	}
	if m.PrimaryNodeID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.PrimaryNodeID))
	}
	return i, nil
}

func (m *RotateSegmentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RotateSegmentRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.NodeID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.NodeID))
	}
	if m.OldSegmentID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.OldSegmentID))
	}
	if len(m.OldLastMessageID) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(len(m.OldLastMessageID)))
		i += copy(dAtA[i:], m.OldLastMessageID)
	}
	if m.OldSize != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(m.OldSize))
	}
	if len(m.OldSha1) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(len(m.OldSha1)))
		i += copy(dAtA[i:], m.OldSha1)
	}
	if len(m.NewFirstMessageID) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintNodeRpc(dAtA, i, uint64(len(m.NewFirstMessageID)))
		i += copy(dAtA[i:], m.NewFirstMessageID)
	}
	return i, nil
}

func encodeVarintNodeRpc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *OpenSegmentRequest) Size() (n int) {
	var l int
	_ = l
	if m.NodeID != 0 {
		n += 1 + sovNodeRpc(uint64(m.NodeID))
	}
	if m.Topic != nil {
		l = m.Topic.Size()
		n += 1 + l + sovNodeRpc(uint64(l))
	}
	l = len(m.FirstMessageID)
	if l > 0 {
		n += 1 + l + sovNodeRpc(uint64(l))
	}
	return n
}

func (m *OpenSegmentResponse) Size() (n int) {
	var l int
	_ = l
	if m.SegmentID != 0 {
		n += 1 + sovNodeRpc(uint64(m.SegmentID))
	}
	if m.PrimaryNodeID != 0 {
		n += 1 + sovNodeRpc(uint64(m.PrimaryNodeID))
	}
	return n
}

func (m *RotateSegmentRequest) Size() (n int) {
	var l int
	_ = l
	if m.NodeID != 0 {
		n += 1 + sovNodeRpc(uint64(m.NodeID))
	}
	if m.OldSegmentID != 0 {
		n += 1 + sovNodeRpc(uint64(m.OldSegmentID))
	}
	l = len(m.OldLastMessageID)
	if l > 0 {
		n += 1 + l + sovNodeRpc(uint64(l))
	}
	if m.OldSize != 0 {
		n += 1 + sovNodeRpc(uint64(m.OldSize))
	}
	l = len(m.OldSha1)
	if l > 0 {
		n += 1 + l + sovNodeRpc(uint64(l))
	}
	l = len(m.NewFirstMessageID)
	if l > 0 {
		n += 1 + l + sovNodeRpc(uint64(l))
	}
	return n
}

func sovNodeRpc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozNodeRpc(x uint64) (n int) {
	return sovNodeRpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OpenSegmentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpenSegmentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpenSegmentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Topic", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Topic == nil {
				m.Topic = &client.NamespaceName{}
			}
			if err := m.Topic.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstMessageID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstMessageID = append(m.FirstMessageID[:0], dAtA[iNdEx:postIndex]...)
			if m.FirstMessageID == nil {
				m.FirstMessageID = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OpenSegmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpenSegmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpenSegmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SegmentID", wireType)
			}
			m.SegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrimaryNodeID", wireType)
			}
			m.PrimaryNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrimaryNodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RotateSegmentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RotateSegmentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RotateSegmentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldSegmentID", wireType)
			}
			m.OldSegmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldSegmentID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldLastMessageID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldLastMessageID = append(m.OldLastMessageID[:0], dAtA[iNdEx:postIndex]...)
			if m.OldLastMessageID == nil {
				m.OldLastMessageID = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldSize", wireType)
			}
			m.OldSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldSize |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldSha1", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OldSha1 = append(m.OldSha1[:0], dAtA[iNdEx:postIndex]...)
			if m.OldSha1 == nil {
				m.OldSha1 = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewFirstMessageID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNodeRpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewFirstMessageID = append(m.NewFirstMessageID[:0], dAtA[iNdEx:postIndex]...)
			if m.NewFirstMessageID == nil {
				m.NewFirstMessageID = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodeRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodeRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNodeRpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNodeRpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeRpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthNodeRpc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowNodeRpc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipNodeRpc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthNodeRpc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNodeRpc   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("node_rpc.proto", fileDescriptor_node_rpc_35e65d3ddca5348d) }

var fileDescriptor_node_rpc_35e65d3ddca5348d = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x65, 0x43, 0x9b, 0xd0, 0x69, 0x62, 0x92, 0xad, 0x11, 0x21, 0x12, 0x71, 0x94, 0x72, 0xc8,
	0x01, 0xb9, 0x6a, 0x2b, 0x21, 0x21, 0x71, 0x4a, 0xa3, 0x4a, 0x96, 0x20, 0xa9, 0x8c, 0xc4, 0xa1,
	0x17, 0x6b, 0xc9, 0x4e, 0x53, 0x4b, 0xb6, 0xd7, 0xb1, 0x17, 0x2a, 0x7a, 0xe0, 0x1b, 0xf8, 0x10,
	0xce, 0xdc, 0xb8, 0x73, 0xe4, 0x0b, 0x2c, 0xb4, 0xfc, 0x08, 0x5a, 0x3b, 0x25, 0x4e, 0x1a, 0x21,
	0xd4, 0xdb, 0xcc, 0xbc, 0x19, 0xbf, 0xb7, 0xf3, 0xc6, 0x60, 0x44, 0x82, 0xa3, 0x97, 0xc4, 0x53,
	0x3b, 0x4e, 0x84, 0x14, 0xd4, 0xf0, 0x85, 0x8d, 0x1f, 0x31, 0x92, 0x12, 0x13, 0x3b, 0x9c, 0x77,
	0x1e, 0x4f, 0x03, 0x1f, 0x23, 0x79, 0x70, 0x53, 0x0b, 0xe7, 0x45, 0x63, 0xc7, 0x9c, 0x89, 0x99,
	0xc8, 0xc3, 0x03, 0x1d, 0x15, 0xd5, 0xfe, 0x57, 0x02, 0x74, 0x12, 0x63, 0xf4, 0x16, 0x67, 0x21,
	0x46, 0xd2, 0xc5, 0xf9, 0x07, 0x4c, 0x25, 0xdd, 0x87, 0x5a, 0xce, 0xe3, 0xf3, 0x36, 0xe9, 0x91,
	0xc1, 0xd6, 0x10, 0x54, 0x66, 0x55, 0xc7, 0x82, 0xa3, 0x33, 0x72, 0xab, 0x1a, 0x72, 0x38, 0x3d,
	0x86, 0x6d, 0x29, 0x62, 0x7f, 0xda, 0xae, 0xf4, 0xc8, 0x60, 0xf7, 0xe8, 0xa9, 0xbd, 0x2a, 0xc5,
	0x1e, 0xb3, 0x10, 0xd3, 0x98, 0x4d, 0x51, 0x07, 0x6e, 0xd1, 0x4b, 0x5f, 0x41, 0xf3, 0xc2, 0x4f,
	0x52, 0xe9, 0x85, 0x98, 0xa6, 0x6c, 0x96, 0x53, 0xdc, 0xef, 0x91, 0x41, 0x7d, 0x48, 0x55, 0x66,
	0x19, 0xa7, 0x1a, 0x7b, 0x53, 0x40, 0xce, 0xc8, 0x35, 0x2e, 0xca, 0x39, 0xef, 0x7f, 0x86, 0xbd,
	0x15, 0xb5, 0x69, 0x2c, 0xa2, 0x14, 0xe9, 0x73, 0x80, 0xb4, 0x28, 0x2d, 0x15, 0x37, 0x54, 0x66,
	0xed, 0x2c, 0x1a, 0x9d, 0x91, 0xbb, 0xb3, 0x68, 0x70, 0x38, 0x7d, 0x09, 0x0f, 0xe3, 0xc4, 0x0f,
	0x59, 0xf2, 0xc9, 0xbb, 0x79, 0x64, 0x25, 0x1f, 0x69, 0xa9, 0xcc, 0x6a, 0x9c, 0x15, 0xd0, 0xe2,
	0xad, 0x8d, 0xb8, 0x94, 0xf2, 0xfe, 0xb7, 0x0a, 0x98, 0xae, 0x90, 0x4c, 0xe2, 0x5d, 0x16, 0xf6,
	0x02, 0x0c, 0x11, 0x70, 0xaf, 0x24, 0xb5, 0xe0, 0x6d, 0xaa, 0xcc, 0xaa, 0x4f, 0x02, 0xbe, 0x54,
	0x5b, 0x17, 0xcb, 0x8c, 0xd3, 0x13, 0xd8, 0xd3, 0x73, 0x01, 0xdb, 0xb4, 0x36, 0x53, 0x65, 0x56,
	0x73, 0x12, 0xf0, 0xd7, 0xac, 0xbc, 0xb8, 0xa6, 0x58, 0xad, 0x70, 0xfa, 0x04, 0x1e, 0xe4, 0xe4,
	0xfe, 0x35, 0xb6, 0xb7, 0x34, 0xad, 0x5b, 0xd3, 0x24, 0xfe, 0x35, 0xfe, 0x85, 0x2e, 0xd9, 0x61,
	0x7b, 0x5b, 0x7f, 0xb4, 0x80, 0x2e, 0xd9, 0x21, 0x3d, 0x05, 0x33, 0xc2, 0x2b, 0xef, 0x96, 0x65,
	0xd5, 0x9c, 0xfb, 0x91, 0xca, 0xac, 0xd6, 0x18, 0xaf, 0xd6, 0x5c, 0x6b, 0x45, 0x6b, 0x25, 0x7e,
	0xf4, 0x9d, 0x40, 0x4d, 0x6f, 0xc3, 0x3d, 0x3b, 0xa1, 0xef, 0x60, 0xb7, 0x64, 0x22, 0xed, 0xaf,
	0xdf, 0xcd, 0xed, 0x7b, 0xec, 0xec, 0xff, 0xb3, 0x67, 0x71, 0x05, 0xe7, 0xd0, 0x58, 0xf1, 0x86,
	0x3e, 0x5b, 0x9f, 0xda, 0x64, 0xdd, 0x7f, 0x7d, 0x7b, 0x68, 0xfe, 0x50, 0x5d, 0xf2, 0x53, 0x75,
	0xc9, 0x2f, 0xd5, 0x25, 0x5f, 0x7e, 0x77, 0xef, 0x9d, 0x57, 0xc2, 0xf9, 0xfb, 0x6a, 0xfe, 0x13,
	0x1d, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x58, 0x45, 0xaf, 0x95, 0x03, 0x00, 0x00,
}
