// Code generated by ./generator/main.go. DO NOT EDIT.
package v1

//go:generate go run ./generator ./amqp1-0-0.go  ./types.bare.xml ./transport.bare.xml ./messaging.bare.xml ./security.bare.xml

import (
	"encoding/hex"
	"time"

	"github.com/gogo/protobuf/types"
)

var _ = time.Time{}
var _ = types.Struct{}

type UUID [16]byte

func (u UUID) String() string {
	var x [36]byte
	hex.Encode(x[:8], u[:4])
	x[8] = '-'
	hex.Encode(x[9:13], u[4:6])
	x[13] = '-'
	hex.Encode(x[14:18], u[6:8])
	x[18] = '-'
	hex.Encode(x[19:23], u[8:10])
	x[23] = '-'
	hex.Encode(x[24:], u[10:])
	return string(x[:])
}

type Frame interface {
	isFrame()
}

type ErrorCondition interface {
	isErrorCondition()
}

type Section interface {
	isSection()
}

type MessageID interface {
	isMessageID()
}

type Address interface {
	isAddress()
}

type DeliveryState interface {
	isDeliveryState()
}

type Outcome interface {
	isOutcome()
}

type DistributionMode interface {
	isDistributionMode()
}

type LifetimePolicy interface {
	isLifetimePolicy()
}

type SASLFrame interface {
	isSASLFrame()
}

const (
	NullEncoding = 0x40
)

const (
	BooleanEncoding      = 0x56
	BooleanTrueEncoding  = 0x41
	BooleanFalseEncoding = 0x42
)

const (
	UbyteEncoding = 0x50
)

const (
	UshortEncoding = 0x60
)

const (
	UintEncoding          = 0x70
	UintSmalluintEncoding = 0x52
	UintUint0Encoding     = 0x43
)

const (
	UlongEncoding           = 0x80
	UlongSmallulongEncoding = 0x53
	UlongUlong0Encoding     = 0x44
)

const (
	ByteEncoding = 0x51
)

const (
	ShortEncoding = 0x61
)

const (
	IntEncoding         = 0x71
	IntSmallintEncoding = 0x54
)

const (
	LongEncoding          = 0x81
	LongSmalllongEncoding = 0x55
)

const (
	FloatIeee754Encoding = 0x72
)

const (
	DoubleIeee754Encoding = 0x82
)

const (
	Decimal32Ieee754Encoding = 0x74
)

const (
	Decimal64Ieee754Encoding = 0x84
)

const (
	Decimal128Ieee754Encoding = 0x94
)

const (
	CharUtf32Encoding = 0x73
)

const (
	TimestampMs64Encoding = 0x83
)

const (
	UUIDEncoding = 0x98
)

const (
	BinaryVbin8Encoding  = 0xa0
	BinaryVbin32Encoding = 0xb0
)

const (
	StringStr8Utf8Encoding  = 0xa1
	StringStr32Utf8Encoding = 0xb1
)

const (
	SymbolSym8Encoding  = 0xa3
	SymbolSym32Encoding = 0xb3
)

const (
	ListList0Encoding  = 0x45
	ListList8Encoding  = 0xc0
	ListList32Encoding = 0xd0
)

const (
	MapMap8Encoding  = 0xc1
	MapMap32Encoding = 0xd1
)

const (
	ArrayArray8Encoding  = 0xe0
	ArrayArray32Encoding = 0xf0
)

const (
	OpenName       = "amqp:open:list"
	OpenDescriptor = 0x0000000000000010
)

type Open struct {
	ContainerID         string
	Hostname            string
	MaxFrameSize        uint32
	ChannelMax          uint16
	IdleTimeOut         Milliseconds
	OutgoingLocales     []IETFLanguageTag
	IncomingLocales     []IETFLanguageTag
	OfferedCapabilities []string
	DesiredCapabilities []string
	Properties          *Fields
}

func (*Open) isFrame() {}

func (f *Open) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Open) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	BeginName       = "amqp:begin:list"
	BeginDescriptor = 0x0000000000000011
)

type Begin struct {
	RemoteChannel       uint16
	NextOutgoingID      TransferNumber
	IncomingWindow      uint32
	OutgoingWindow      uint32
	HandleMax           Handle
	OfferedCapabilities []string
	DesiredCapabilities []string
	Properties          *Fields
}

func (*Begin) isFrame() {}

func (f *Begin) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Begin) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	AttachName       = "amqp:attach:list"
	AttachDescriptor = 0x0000000000000012
)

type Attach struct {
	Name                 string
	Handle               Handle
	Role                 Role
	SndSettleMode        SenderSettleMode
	RcvSettleMode        ReceiverSettleMode
	Source               *Source
	Target               *Target
	Unsettled            *types.Struct
	IncompleteUnsettled  bool
	InitialDeliveryCount SequenceNo
	MaxMessageSize       uint64
	OfferedCapabilities  []string
	DesiredCapabilities  []string
	Properties           *Fields
}

func (*Attach) isFrame() {}

func (f *Attach) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Attach) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	FlowName       = "amqp:flow:list"
	FlowDescriptor = 0x0000000000000013
)

type Flow struct {
	NextIncomingID TransferNumber
	IncomingWindow uint32
	NextOutgoingID TransferNumber
	OutgoingWindow uint32
	Handle         Handle
	DeliveryCount  SequenceNo
	LinkCredit     uint32
	Available      uint32
	Drain          bool
	Echo           bool
	Properties     *Fields
}

func (*Flow) isFrame() {}

func (f *Flow) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Flow) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	TransferName       = "amqp:transfer:list"
	TransferDescriptor = 0x0000000000000014
)

type Transfer struct {
	Handle        Handle
	DeliveryID    DeliveryNumber
	DeliveryTag   DeliveryTag
	MessageFormat MessageFormat
	Settled       bool
	More          bool
	RcvSettleMode ReceiverSettleMode
	State         DeliveryState
	Resume        bool
	Aborted       bool
	Batchable     bool
}

func (*Transfer) isFrame() {}

func (f *Transfer) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Transfer) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	DispositionName       = "amqp:disposition:list"
	DispositionDescriptor = 0x0000000000000015
)

type Disposition struct {
	Role      Role
	First     DeliveryNumber
	Last      DeliveryNumber
	Settled   bool
	State     DeliveryState
	Batchable bool
}

func (*Disposition) isFrame() {}

func (f *Disposition) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Disposition) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	DetachName       = "amqp:detach:list"
	DetachDescriptor = 0x0000000000000016
)

type Detach struct {
	Handle Handle
	Closed bool
	Error  *Error
}

func (*Detach) isFrame() {}

func (f *Detach) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Detach) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	EndName       = "amqp:end:list"
	EndDescriptor = 0x0000000000000017
)

type End struct {
	Error *Error
}

func (*End) isFrame() {}

func (f *End) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *End) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	CloseName       = "amqp:close:list"
	CloseDescriptor = 0x0000000000000018
)

type Close struct {
	Error *Error
}

func (*Close) isFrame() {}

func (f *Close) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Close) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	Port            = 5672
	SecurePort      = 5671
	Major           = 1
	Minor           = 0
	Revision        = 0
	MinMaxFrameSize = 512
)

type Role bool

const (
	SenderRole   Role = false
	ReceiverRole Role = true
)

type SenderSettleMode uint8

const (
	UnsettledSenderSettleMode SenderSettleMode = 0
	SettledSenderSettleMode   SenderSettleMode = 1
	MixedSenderSettleMode     SenderSettleMode = 2
)

type ReceiverSettleMode uint8

const (
	FirstReceiverSettleMode  ReceiverSettleMode = 0
	SecondReceiverSettleMode ReceiverSettleMode = 1
)

type Handle uint32

type Seconds uint32

type Milliseconds uint32

type DeliveryTag []byte

type DeliveryNumber uint32

type TransferNumber uint32

type SequenceNo uint32

type MessageFormat uint32

type IETFLanguageTag string

type Fields types.Struct

const (
	ErrorName       = "amqp:error:list"
	ErrorDescriptor = 0x000000000000001d
)

type Error struct {
	Condition   string
	Description string
	Info        *Fields
}

func (f *Error) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Error) Unmarshal(data []byte) error {
	panic("implement me")
}

type AMQPError string

const (
	InternalErrorAMQPError         AMQPError = "amqp:internal-error"
	NotFoundAMQPError              AMQPError = "amqp:not-found"
	UnauthorizedAccessAMQPError    AMQPError = "amqp:unauthorized-access"
	DecodeErrorAMQPError           AMQPError = "amqp:decode-error"
	ResourceLimitExceededAMQPError AMQPError = "amqp:resource-limit-exceeded"
	NotAllowedAMQPError            AMQPError = "amqp:not-allowed"
	InvalidFieldAMQPError          AMQPError = "amqp:invalid-field"
	NotImplementedAMQPError        AMQPError = "amqp:not-implemented"
	ResourceLockedAMQPError        AMQPError = "amqp:resource-locked"
	PreconditionFailedAMQPError    AMQPError = "amqp:precondition-failed"
	ResourceDeletedAMQPError       AMQPError = "amqp:resource-deleted"
	IllegalStateAMQPError          AMQPError = "amqp:illegal-state"
	FrameSizeTooSmallAMQPError     AMQPError = "amqp:frame-size-too-small"
)

func (AMQPError) isErrorCondition() {}

type ConnectionError string

const (
	ConnectionForcedConnectionError ConnectionError = "amqp:connection:forced"
	FramingErrorConnectionError     ConnectionError = "amqp:connection:framing-error"
	RedirectConnectionError         ConnectionError = "amqp:connection:redirect"
)

func (ConnectionError) isErrorCondition() {}

type SessionError string

const (
	WindowViolationSessionError  SessionError = "amqp:session:window-violation"
	ErrantLinkSessionError       SessionError = "amqp:session:errant-link"
	HandleInUseSessionError      SessionError = "amqp:session:handle-in-use"
	UnattachedHandleSessionError SessionError = "amqp:session:unattached-handle"
)

func (SessionError) isErrorCondition() {}

type LinkError string

const (
	DetachForcedLinkError          LinkError = "amqp:link:detach-forced"
	TransferLimitExceededLinkError LinkError = "amqp:link:transfer-limit-exceeded"
	MessageSizeExceededLinkError   LinkError = "amqp:link:message-size-exceeded"
	RedirectLinkError              LinkError = "amqp:link:redirect"
	StolenLinkError                LinkError = "amqp:link:stolen"
)

func (LinkError) isErrorCondition() {}

const ()

const (
	HeaderName       = "amqp:header:list"
	HeaderDescriptor = 0x0000000000000070
)

type Header struct {
	Durable       bool
	Priority      uint8
	Ttl           Milliseconds
	FirstAcquirer bool
	DeliveryCount uint32
}

func (*Header) isSection() {}

func (f *Header) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Header) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	DeliveryAnnotationsName       = "amqp:delivery-annotations:map"
	DeliveryAnnotationsDescriptor = 0x0000000000000071
)

type DeliveryAnnotations types.Struct

func (DeliveryAnnotations) isSection() {}

const (
	MessageAnnotationsName       = "amqp:message-annotations:map"
	MessageAnnotationsDescriptor = 0x0000000000000072
)

type MessageAnnotations types.Struct

func (MessageAnnotations) isSection() {}

const (
	PropertiesName       = "amqp:properties:list"
	PropertiesDescriptor = 0x0000000000000073
)

type Properties struct {
	MessageID          MessageID
	UserID             []byte
	To                 Address
	Subject            string
	ReplyTo            Address
	CorrelationID      MessageID
	ContentType        string
	ContentEncoding    string
	AbsoluteExpiryTime time.Time
	CreationTime       time.Time
	GroupID            string
	GroupSequence      SequenceNo
	ReplyToGroupID     string
}

func (*Properties) isSection() {}

func (f *Properties) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Properties) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	ApplicationPropertiesName       = "amqp:application-properties:map"
	ApplicationPropertiesDescriptor = 0x0000000000000074
)

type ApplicationProperties types.Struct

func (ApplicationProperties) isSection() {}

const (
	DataName       = "amqp:data:binary"
	DataDescriptor = 0x0000000000000075
)

type Data []byte

func (Data) isSection() {}

const (
	FooterName       = "amqp:footer:map"
	FooterDescriptor = 0x0000000000000078
)

type Footer types.Struct

func (Footer) isSection() {}

type Annotations types.Struct

type MessageIDUlong uint64

func (MessageIDUlong) isMessageID() {}

type MessageIDUUID UUID

func (MessageIDUUID) isMessageID() {}

type MessageIDBinary []byte

func (MessageIDBinary) isMessageID() {}

type MessageIDString string

func (MessageIDString) isMessageID() {}

type AddressString string

func (AddressString) isAddress() {}

const (
	ReceivedName       = "amqp:received:list"
	ReceivedDescriptor = 0x0000000000000023
)

type Received struct {
	SectionNumber uint32
	SectionOffset uint64
}

func (*Received) isDeliveryState() {}

func (f *Received) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Received) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	AcceptedName       = "amqp:accepted:list"
	AcceptedDescriptor = 0x0000000000000024
)

type Accepted struct {
}

func (*Accepted) isDeliveryState() {}

func (*Accepted) isOutcome() {}

func (f *Accepted) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Accepted) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	RejectedName       = "amqp:rejected:list"
	RejectedDescriptor = 0x0000000000000025
)

type Rejected struct {
	Error *Error
}

func (*Rejected) isDeliveryState() {}

func (*Rejected) isOutcome() {}

func (f *Rejected) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Rejected) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	ReleasedName       = "amqp:released:list"
	ReleasedDescriptor = 0x0000000000000026
)

type Released struct {
}

func (*Released) isDeliveryState() {}

func (*Released) isOutcome() {}

func (f *Released) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Released) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	ModifiedName       = "amqp:modified:list"
	ModifiedDescriptor = 0x0000000000000027
)

type Modified struct {
	DeliveryFailed     bool
	UndeliverableHere  bool
	MessageAnnotations *Fields
}

func (*Modified) isDeliveryState() {}

func (*Modified) isOutcome() {}

func (f *Modified) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Modified) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	SourceName       = "amqp:source:list"
	SourceDescriptor = 0x0000000000000028
)

type Source struct {
	Address               Address
	Durable               TerminusDurability
	ExpiryPolicy          TerminusExpiryPolicy
	Timeout               Seconds
	Dynamic               bool
	DynamicNodeProperties *NodeProperties
	DistributionMode      string
	Filter                *FilterSet
	DefaultOutcome        Outcome
	Outcomes              []string
	Capabilities          []string
}

func (*Source) isSource() {}

func (f *Source) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Source) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	TargetName       = "amqp:target:list"
	TargetDescriptor = 0x0000000000000029
)

type Target struct {
	Address               Address
	Durable               TerminusDurability
	ExpiryPolicy          TerminusExpiryPolicy
	Timeout               Seconds
	Dynamic               bool
	DynamicNodeProperties *NodeProperties
	Capabilities          []string
}

func (*Target) isTarget() {}

func (f *Target) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *Target) Unmarshal(data []byte) error {
	panic("implement me")
}

type TerminusDurability uint32

const (
	NoneTerminusDurability           TerminusDurability = 0
	ConfigurationTerminusDurability  TerminusDurability = 1
	UnsettledStateTerminusDurability TerminusDurability = 2
)

type TerminusExpiryPolicy string

const (
	LinkDetachTerminusExpiryPolicy      TerminusExpiryPolicy = "link-detach"
	SessionEndTerminusExpiryPolicy      TerminusExpiryPolicy = "session-end"
	ConnectionCloseTerminusExpiryPolicy TerminusExpiryPolicy = "connection-close"
	NeverTerminusExpiryPolicy           TerminusExpiryPolicy = "never"
)

type StdDistMode string

const (
	MoveStdDistMode StdDistMode = "move"
	CopyStdDistMode StdDistMode = "copy"
)

func (StdDistMode) isDistributionMode() {}

type FilterSet types.Struct

type NodeProperties types.Struct

const (
	DeleteOnCloseName       = "amqp:delete-on-close:list"
	DeleteOnCloseDescriptor = 0x000000000000002b
)

type DeleteOnClose struct {
}

func (*DeleteOnClose) isLifetimePolicy() {}

func (f *DeleteOnClose) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *DeleteOnClose) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	DeleteOnNoLinksName       = "amqp:delete-on-no-links:list"
	DeleteOnNoLinksDescriptor = 0x000000000000002c
)

type DeleteOnNoLinks struct {
}

func (*DeleteOnNoLinks) isLifetimePolicy() {}

func (f *DeleteOnNoLinks) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *DeleteOnNoLinks) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	DeleteOnNoMessagesName       = "amqp:delete-on-no-messages:list"
	DeleteOnNoMessagesDescriptor = 0x000000000000002d
)

type DeleteOnNoMessages struct {
}

func (*DeleteOnNoMessages) isLifetimePolicy() {}

func (f *DeleteOnNoMessages) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *DeleteOnNoMessages) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	DeleteOnNoLinksOrMessagesName       = "amqp:delete-on-no-links-or-messages:list"
	DeleteOnNoLinksOrMessagesDescriptor = 0x000000000000002e
)

type DeleteOnNoLinksOrMessages struct {
}

func (*DeleteOnNoLinksOrMessages) isLifetimePolicy() {}

func (f *DeleteOnNoLinksOrMessages) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *DeleteOnNoLinksOrMessages) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	TLSMajor    = 1
	TLSMinor    = 0
	TLSRevision = 0
)

const (
	SASLMajor    = 1
	SASLMinor    = 0
	SASLRevision = 0
)

const (
	SASLMechanismsName       = "amqp:sasl-mechanisms:list"
	SASLMechanismsDescriptor = 0x0000000000000040
)

type SASLMechanisms struct {
	SASLServerMechanisms []string
}

func (*SASLMechanisms) isSASLFrame() {}

func (f *SASLMechanisms) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *SASLMechanisms) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	SASLInitName       = "amqp:sasl-init:list"
	SASLInitDescriptor = 0x0000000000000041
)

type SASLInit struct {
	Mechanism       string
	InitialResponse []byte
	Hostname        string
}

func (*SASLInit) isSASLFrame() {}

func (f *SASLInit) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *SASLInit) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	SASLChallengeName       = "amqp:sasl-challenge:list"
	SASLChallengeDescriptor = 0x0000000000000042
)

type SASLChallenge struct {
	Challenge []byte
}

func (*SASLChallenge) isSASLFrame() {}

func (f *SASLChallenge) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *SASLChallenge) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	SASLResponseName       = "amqp:sasl-response:list"
	SASLResponseDescriptor = 0x0000000000000043
)

type SASLResponse struct {
	Response []byte
}

func (*SASLResponse) isSASLFrame() {}

func (f *SASLResponse) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *SASLResponse) Unmarshal(data []byte) error {
	panic("implement me")
}

const (
	SASLOutcomeName       = "amqp:sasl-outcome:list"
	SASLOutcomeDescriptor = 0x0000000000000044
)

type SASLOutcome struct {
	Code           SASLCode
	AdditionalData []byte
}

func (*SASLOutcome) isSASLFrame() {}

func (f *SASLOutcome) Marshal() ([]byte, error) {
	panic("implement me")
}

func (f *SASLOutcome) Unmarshal(data []byte) error {
	panic("implement me")
}

type SASLCode uint8

const (
	OkSASLCode      SASLCode = 0
	AuthSASLCode    SASLCode = 1
	SysSASLCode     SASLCode = 2
	SysPermSASLCode SASLCode = 3
	SysTempSASLCode SASLCode = 4
)
